// 発見タブのコンテンツ(ピンインの声調・漢字入門・日常フレーズ・流行フレーズ・ネイティブ表現)

const PINYIN_TONES = [
  { tone: 1, mark: "ā", name: "第1声", curve: "高く平らに", tip: "高い音のまま、まっすぐ伸ばす。「あー」と歌うように。", char: "妈", pinyin: "mā", meaning: "お母さん" },
  { tone: 2, mark: "á", name: "第2声", curve: "下から上へ", tip: "驚いて「えっ?」と聞き返すように、低めから一気に上げる。", char: "麻", pinyin: "má", meaning: "麻・しびれる" },
  { tone: 3, mark: "ǎ", name: "第3声", curve: "低く抑える", tip: "低く沈める。単独や文末では最後に少し上がる。「へぇ〜」と感心するように。", char: "马", pinyin: "mǎ", meaning: "馬" },
  { tone: 4, mark: "à", name: "第4声", curve: "上から下へ", tip: "高いところから一気に落とす。カラスの「カァ!」のように短く強く。", char: "骂", pinyin: "mà", meaning: "ののしる" },
  { tone: 0, mark: "a", name: "軽声", curve: "軽く短く", tip: "前の音に続けて軽く短く添える。例: 妈妈 māma の2文字目。", char: "吗", pinyin: "ma", meaning: "〜か?(疑問)" },
];

// 漢字入門: 基本の漢字(書き順アニメーションのデータは hanzi_strokes.js)
const HANZI_GROUPS = [
  {
    id: "numbers",
    title: "数字",
    icon: "🔢",
    chars: [
      { ch: "一", pinyin: "yī", meaning: "1", note: "横棒1本で「1」。", words: [["第一", "dì yī", "第一・1番目"], ["一起", "yìqǐ", "一緒に"]] },
      { ch: "二", pinyin: "èr", meaning: "2", note: "横棒2本。数える時は「两 liǎng」を使うことが多い(两个人)。", words: [["二月", "èr yuè", "2月"], ["第二", "dì èr", "2番目"]] },
      { ch: "三", pinyin: "sān", meaning: "3", note: "横棒3本。", words: [["三天", "sān tiān", "3日間"], ["星期三", "xīngqīsān", "水曜日"]] },
      { ch: "四", pinyin: "sì", meaning: "4", note: "日本語と同じ形。", words: [["四季", "sìjì", "四季"], ["四月", "sì yuè", "4月"]] },
      { ch: "五", pinyin: "wǔ", meaning: "5", note: "日本語と同じ形。", words: [["五点", "wǔ diǎn", "5時"], ["五月", "wǔ yuè", "5月"]] },
      { ch: "六", pinyin: "liù", meaning: "6", note: "日本語と同じ形。", words: [["六月", "liù yuè", "6月"], ["六点", "liù diǎn", "6時"]] },
      { ch: "七", pinyin: "qī", meaning: "7", note: "日本語と同じ形。", words: [["七天", "qī tiān", "7日間"], ["七点", "qī diǎn", "7時"]] },
      { ch: "八", pinyin: "bā", meaning: "8", note: "「発(fā)」と音が似ているので縁起の良い数字とされる。", words: [["八月", "bā yuè", "8月"], ["八点", "bā diǎn", "8時"]] },
      { ch: "九", pinyin: "jiǔ", meaning: "9", note: "「久(jiǔ)」と同じ音で、長く続く縁起の良い数字。", words: [["九月", "jiǔ yuè", "9月"], ["九点", "jiǔ diǎn", "9時"]] },
      { ch: "十", pinyin: "shí", meaning: "10", note: "日本語と同じ形。", words: [["十分", "shífēn", "とても"], ["十月", "shí yuè", "10月"]] },
      { ch: "百", pinyin: "bǎi", meaning: "百", note: "日本語と同じ形。", words: [["一百", "yìbǎi", "100"], ["百货", "bǎihuò", "百貨"]] },
      { ch: "千", pinyin: "qiān", meaning: "千", note: "日本語と同じ形。", words: [["一千", "yìqiān", "1000"], ["千万", "qiānwàn", "くれぐれも・必ず"]] },
    ],
  },
  {
    id: "nature",
    title: "自然",
    icon: "⛰️",
    chars: [
      { ch: "日", pinyin: "rì", meaning: "太陽・日", note: "太陽の形から。", words: [["日本", "Rìběn", "日本"], ["生日", "shēngrì", "誕生日"]] },
      { ch: "月", pinyin: "yuè", meaning: "月", note: "三日月の形から。", words: [["月亮", "yuèliang", "(空の)月"], ["一月", "yī yuè", "1月"]] },
      { ch: "山", pinyin: "shān", meaning: "山", note: "3つの峰の形から。", words: [["爬山", "páshān", "山登り"], ["山上", "shān shang", "山の上"]] },
      { ch: "水", pinyin: "shuǐ", meaning: "水", note: "流れる水の形から。", words: [["喝水", "hē shuǐ", "水を飲む"], ["水果", "shuǐguǒ", "果物"]] },
      { ch: "火", pinyin: "huǒ", meaning: "火", note: "燃える炎の形から。", words: [["火车", "huǒchē", "列車"], ["火锅", "huǒguō", "火鍋"]] },
      { ch: "木", pinyin: "mù", meaning: "木", note: "木の形から。「木」は材木の意味で、生えている木は「树 shù」。", words: [["木头", "mùtou", "木材"], ["树木", "shùmù", "樹木"]] },
      { ch: "雨", pinyin: "yǔ", meaning: "雨", note: "空から雨粒が落ちる形から。", words: [["下雨", "xià yǔ", "雨が降る"], ["雨伞", "yǔsǎn", "傘"]] },
      { ch: "天", pinyin: "tiān", meaning: "空・日", note: "「日」の意味でもよく使う(今天=今日)。", words: [["今天", "jīntiān", "今日"], ["天气", "tiānqì", "天気"]] },
      { ch: "田", pinyin: "tián", meaning: "田", note: "区切られた田んぼの形から。", words: [["田地", "tiándì", "田畑"], ["种田", "zhòngtián", "畑を耕す"]] },
    ],
  },
  {
    id: "people",
    title: "人と体",
    icon: "🙋",
    chars: [
      { ch: "人", pinyin: "rén", meaning: "人", note: "横から見た人の形から。", words: [["中国人", "Zhōngguórén", "中国人"], ["大人", "dàren", "大人"]] },
      { ch: "口", pinyin: "kǒu", meaning: "口", note: "口の形から。家族の人数を数える量詞にもなる(四口人)。", words: [["人口", "rénkǒu", "人口"], ["门口", "ménkǒu", "入口"]] },
      { ch: "手", pinyin: "shǒu", meaning: "手", note: "指を広げた手の形から。", words: [["手机", "shǒujī", "携帯電話"], ["洗手间", "xǐshǒujiān", "トイレ"]] },
      { ch: "目", pinyin: "mù", meaning: "目", note: "目の形から。会話で「目」は「眼睛 yǎnjing」と言う。", words: [["目标", "mùbiāo", "目標"], ["题目", "tímù", "題目・問題"]] },
      { ch: "耳", pinyin: "ěr", meaning: "耳", note: "耳の形から。", words: [["耳朵", "ěrduo", "耳"], ["耳机", "ěrjī", "イヤホン"]] },
      { ch: "心", pinyin: "xīn", meaning: "心", note: "心臓の形から。", words: [["小心", "xiǎoxīn", "気をつける"], ["开心", "kāixīn", "楽しい"]] },
      { ch: "女", pinyin: "nǚ", meaning: "女", note: "ひざまずく女性の形から。", words: [["女儿", "nǚ'ér", "娘"], ["女朋友", "nǚpéngyou", "彼女"]] },
      { ch: "子", pinyin: "zǐ", meaning: "子", note: "子どもの形から。名詞の後ろに付くと軽声 zi になる(桌子)。", words: [["孩子", "háizi", "子ども"], ["桌子", "zhuōzi", "机"]] },
      { ch: "大", pinyin: "dà", meaning: "大きい", note: "両手両足を広げた人の形から。", words: [["大学", "dàxué", "大学"], ["大家", "dàjiā", "みなさん"]] },
      { ch: "小", pinyin: "xiǎo", meaning: "小さい", note: "小さな点3つから。", words: [["小时", "xiǎoshí", "〜時間"], ["小孩", "xiǎohái", "子ども"]] },
    ],
  },
  {
    id: "direction",
    title: "方向・位置",
    icon: "🧭",
    chars: [
      { ch: "上", pinyin: "shàng", meaning: "上", note: "基準線の上にある印から。", words: [["上班", "shàngbān", "出勤する"], ["晚上", "wǎnshang", "夜"]] },
      { ch: "下", pinyin: "xià", meaning: "下", note: "基準線の下にある印から。", words: [["下午", "xiàwǔ", "午後"], ["下班", "xiàbān", "退勤する"]] },
      { ch: "中", pinyin: "zhōng", meaning: "中", note: "真ん中を貫く形から。", words: [["中国", "Zhōngguó", "中国"], ["中午", "zhōngwǔ", "昼"]] },
      { ch: "左", pinyin: "zuǒ", meaning: "左", note: "日本語と同じ形。", words: [["左边", "zuǒbian", "左側"], ["左手", "zuǒshǒu", "左手"]] },
      { ch: "右", pinyin: "yòu", meaning: "右", note: "日本語と同じ形。", words: [["右边", "yòubian", "右側"], ["左右", "zuǒyòu", "〜くらい"]] },
      { ch: "东", pinyin: "dōng", meaning: "東", note: "日本の「東」の簡体字。", words: [["东西", "dōngxi", "もの"], ["东京", "Dōngjīng", "東京"]] },
      { ch: "西", pinyin: "xī", meaning: "西", note: "日本語と同じ形。", words: [["西瓜", "xīguā", "スイカ"], ["西安", "Xī'ān", "西安"]] },
      { ch: "南", pinyin: "nán", meaning: "南", note: "日本語と同じ形。", words: [["南方", "nánfāng", "南の地方"], ["南京", "Nánjīng", "南京"]] },
      { ch: "北", pinyin: "běi", meaning: "北", note: "日本語と同じ形。", words: [["北京", "Běijīng", "北京"], ["东北", "dōngběi", "東北"]] },
    ],
  },
  {
    id: "daily",
    title: "よく使う字",
    icon: "⭐",
    chars: [
      { ch: "我", pinyin: "wǒ", meaning: "私", note: "一人称。男女とも使う。", words: [["我们", "wǒmen", "私たち"], ["我的", "wǒ de", "私の"]] },
      { ch: "你", pinyin: "nǐ", meaning: "あなた", note: "日本語では使わない字。丁寧に言うときは「您 nín」。", words: [["你好", "nǐ hǎo", "こんにちは"], ["你们", "nǐmen", "あなたたち"]] },
      { ch: "他", pinyin: "tā", meaning: "彼", note: "女性は「她 tā」(発音は同じ)。", words: [["他们", "tāmen", "彼ら"], ["其他", "qítā", "その他"]] },
      { ch: "好", pinyin: "hǎo", meaning: "良い", note: "「女」+「子」。", words: [["好吃", "hǎochī", "おいしい"], ["好的", "hǎo de", "いいよ・了解"]] },
      { ch: "是", pinyin: "shì", meaning: "〜である", note: "英語の be 動詞にあたる。", words: [["是的", "shì de", "そうです"], ["但是", "dànshì", "しかし"]] },
      { ch: "不", pinyin: "bù", meaning: "〜ない", note: "否定。第4声の前では bú になる。", words: [["不是", "bú shì", "〜ではない"], ["不要", "bú yào", "要らない"]] },
      { ch: "有", pinyin: "yǒu", meaning: "ある・持つ", note: "否定は「没有 méiyǒu」。", words: [["没有", "méiyǒu", "ない"], ["有名", "yǒumíng", "有名"]] },
      { ch: "吃", pinyin: "chī", meaning: "食べる", note: "「口」+「乞」。", words: [["吃饭", "chīfàn", "ご飯を食べる"], ["好吃", "hǎochī", "おいしい"]] },
      { ch: "喝", pinyin: "hē", meaning: "飲む", note: "「口」へんが付く。", words: [["喝茶", "hē chá", "お茶を飲む"], ["喝酒", "hē jiǔ", "お酒を飲む"]] },
      { ch: "看", pinyin: "kàn", meaning: "見る・読む", note: "目の上に手をかざす形から。", words: [["看书", "kàn shū", "本を読む"], ["好看", "hǎokàn", "きれい・面白い"]] },
      { ch: "说", pinyin: "shuō", meaning: "話す", note: "日本の「説」の簡体字(言べんが「讠」)。", words: [["说话", "shuōhuà", "話す"], ["小说", "xiǎoshuō", "小説"]] },
      { ch: "学", pinyin: "xué", meaning: "学ぶ", note: "日本語と同じ形。", words: [["学生", "xuésheng", "学生"], ["学习", "xuéxí", "勉強する"]] },
      { ch: "家", pinyin: "jiā", meaning: "家", note: "屋根の下に豚がいる形から。", words: [["回家", "huí jiā", "帰宅する"], ["大家", "dàjiā", "みなさん"]] },
      { ch: "国", pinyin: "guó", meaning: "国", note: "日本語と同じ形。", words: [["外国", "wàiguó", "外国"], ["国家", "guójiā", "国家"]] },
      { ch: "车", pinyin: "chē", meaning: "車", note: "日本の「車」の簡体字。", words: [["汽车", "qìchē", "自動車"], ["出租车", "chūzūchē", "タクシー"]] },
      { ch: "门", pinyin: "mén", meaning: "門・ドア", note: "日本の「門」の簡体字。", words: [["开门", "kāi mén", "ドアを開ける"], ["门口", "ménkǒu", "入口"]] },
      { ch: "马", pinyin: "mǎ", meaning: "馬", note: "日本の「馬」の簡体字。", words: [["马上", "mǎshàng", "すぐに"], ["马路", "mǎlù", "大通り"]] },
      { ch: "鱼", pinyin: "yú", meaning: "魚", note: "日本の「魚」の簡体字。", words: [["金鱼", "jīnyú", "金魚"], ["鱼肉", "yúròu", "魚の身"]] },
      { ch: "鸟", pinyin: "niǎo", meaning: "鳥", note: "日本の「鳥」の簡体字。", words: [["小鸟", "xiǎoniǎo", "小鳥"], ["鸟儿", "niǎor", "鳥"]] },
    ],
  },
];

// 日常フレーズ
const DAILY_PHRASES = [
  {
    id: "greeting",
    title: "あいさつ",
    icon: "👋",
    phrases: [
      ["你好", "nǐ hǎo", "こんにちは"],
      ["早上好", "zǎoshang hǎo", "おはようございます"],
      ["晚上好", "wǎnshang hǎo", "こんばんは"],
      ["谢谢", "xièxie", "ありがとう"],
      ["不客气", "bú kèqi", "どういたしまして"],
      ["对不起", "duìbuqǐ", "ごめんなさい"],
      ["没关系", "méi guānxi", "大丈夫です"],
      ["再见", "zàijiàn", "さようなら"],
      ["好久不见", "hǎojiǔ bú jiàn", "お久しぶりです"],
    ],
  },
  {
    id: "intro",
    title: "自己紹介",
    icon: "🙋",
    phrases: [
      ["我叫田中", "wǒ jiào Tiánzhōng", "田中と申します"],
      ["我是日本人", "wǒ shì Rìběnrén", "私は日本人です"],
      ["认识你很高兴", "rènshi nǐ hěn gāoxìng", "お会いできて嬉しいです"],
      ["我在东京工作", "wǒ zài Dōngjīng gōngzuò", "東京で働いています"],
      ["我在学中文", "wǒ zài xué Zhōngwén", "中国語を勉強しています"],
      ["我的爱好是旅游", "wǒ de àihào shì lǚyóu", "趣味は旅行です"],
      ["请多关照", "qǐng duō guānzhào", "よろしくお願いします"],
    ],
  },
  {
    id: "restaurant",
    title: "レストラン",
    icon: "🍜",
    phrases: [
      ["服务员！", "fúwùyuán!", "すみません(店員を呼ぶ)"],
      ["请给我菜单", "qǐng gěi wǒ càidān", "メニューをください"],
      ["有推荐的菜吗？", "yǒu tuījiàn de cài ma?", "おすすめの料理はありますか?"],
      ["我要这个", "wǒ yào zhège", "これをください"],
      ["不要太辣", "bú yào tài là", "辛くしすぎないでください"],
      ["太好吃了！", "tài hǎochī le!", "すごくおいしい!"],
      ["可以打包吗？", "kěyǐ dǎbāo ma?", "持ち帰りできますか?"],
      ["买单", "mǎidān", "お会計お願いします"],
    ],
  },
  {
    id: "shopping",
    title: "買い物",
    icon: "🛍️",
    phrases: [
      ["多少钱？", "duōshao qián?", "いくらですか?"],
      ["太贵了", "tài guì le", "高すぎます"],
      ["便宜一点吧", "piányi yìdiǎn ba", "少し安くしてください"],
      ["可以试试吗？", "kěyǐ shìshi ma?", "試着してもいいですか?"],
      ["有大一点的吗？", "yǒu dà yìdiǎn de ma?", "もう少し大きいのはありますか?"],
      ["可以用微信支付吗？", "kěyǐ yòng Wēixìn zhīfù ma?", "WeChat Payは使えますか?"],
      ["我只是看看", "wǒ zhǐshì kànkan", "見ているだけです"],
    ],
  },
  {
    id: "transport",
    title: "交通・道案内",
    icon: "🚕",
    phrases: [
      ["洗手间在哪儿？", "xǐshǒujiān zài nǎr?", "トイレはどこですか?"],
      ["地铁站怎么走？", "dìtiě zhàn zěnme zǒu?", "地下鉄の駅へはどう行きますか?"],
      ["请到这个地址", "qǐng dào zhège dìzhǐ", "この住所までお願いします"],
      ["在这儿停一下", "zài zhèr tíng yíxià", "ここで止めてください"],
      ["远吗？", "yuǎn ma?", "遠いですか?"],
      ["要多长时间？", "yào duō cháng shíjiān?", "どのくらい時間がかかりますか?"],
      ["请给我发票", "qǐng gěi wǒ fāpiào", "領収書をください"],
    ],
  },
  {
    id: "hotel",
    title: "ホテル",
    icon: "🏨",
    phrases: [
      ["我要办理入住", "wǒ yào bànlǐ rùzhù", "チェックインしたいです"],
      ["我预订了房间", "wǒ yùdìng le fángjiān", "部屋を予約しています"],
      ["几点退房？", "jǐ diǎn tuìfáng?", "チェックアウトは何時ですか?"],
      ["早餐几点开始？", "zǎocān jǐ diǎn kāishǐ?", "朝食は何時からですか?"],
      ["可以寄存行李吗？", "kěyǐ jìcún xíngli ma?", "荷物を預けられますか?"],
      ["房间有点儿冷", "fángjiān yǒudiǎnr lěng", "部屋が少し寒いです"],
    ],
  },
  {
    id: "trouble",
    title: "体調・トラブル",
    icon: "🏥",
    phrases: [
      ["我不舒服", "wǒ bù shūfu", "気分が悪いです"],
      ["我头疼", "wǒ tóu téng", "頭が痛いです"],
      ["附近有医院吗？", "fùjìn yǒu yīyuàn ma?", "近くに病院はありますか?"],
      ["请帮帮我", "qǐng bāngbang wǒ", "助けてください"],
      ["我的钱包丢了", "wǒ de qiánbāo diū le", "財布をなくしました"],
      ["我听不懂", "wǒ tīng bu dǒng", "聞き取れません"],
      ["请再说一遍", "qǐng zài shuō yí biàn", "もう一度言ってください"],
      ["请说慢一点儿", "qǐng shuō màn yìdiǎnr", "もう少しゆっくり話してください"],
    ],
  },
  {
    id: "business",
    title: "仕事",
    icon: "💼",
    phrases: [
      ["请问王经理在吗？", "qǐngwèn Wáng jīnglǐ zài ma?", "王マネージャーはいらっしゃいますか?"],
      ["这是我的名片", "zhè shì wǒ de míngpiàn", "こちらが私の名刺です"],
      ["我们开始开会吧", "wǒmen kāishǐ kāihuì ba", "会議を始めましょう"],
      ["我明白了", "wǒ míngbai le", "分かりました"],
      ["我确认一下", "wǒ quèrèn yíxià", "確認します"],
      ["辛苦了", "xīnkǔ le", "お疲れさまです"],
      ["下周见", "xià zhōu jiàn", "来週お会いしましょう"],
      ["期待与您合作", "qīdài yǔ nín hézuò", "ご一緒できるのを楽しみにしています"],
    ],
  },
];

// 流行フレーズ(ネットスラング)
const TRENDY_PHRASES = [
  { zh: "电灯泡", pinyin: "diàndēngpào", title: "カップルの隣にいる余分な人", art: "💡👫", explain: "直訳は「電球」。デート中の二人のそばにいて、明るく照らしてしまう=お邪魔虫。", ex: ["你们去约会吧，我不想当电灯泡。", "Nǐmen qù yuēhuì ba, wǒ bù xiǎng dāng diàndēngpào.", "二人でデートに行ってきなよ、お邪魔虫になりたくないし。"] },
  { zh: "躺平", pinyin: "tǎngpíng", title: "頑張るのをやめて寝そべる", art: "🛌💤", explain: "競争や出世をあきらめ、最低限の生活で満足する生き方。若者の間で広まった言葉。", ex: ["工作太累了，我想躺平。", "Gōngzuò tài lèi le, wǒ xiǎng tǎngpíng.", "仕事が疲れすぎて、もう寝そべっていたい。"] },
  { zh: "内卷", pinyin: "nèijuǎn", title: "意味のない過当競争", art: "🌀😵", explain: "限られたパイを奪い合って、みんなが消耗していく状態。職場や受験でよく使う。", ex: ["我们公司太内卷了，大家都加班到很晚。", "Wǒmen gōngsī tài nèijuǎn le, dàjiā dōu jiābān dào hěn wǎn.", "うちの会社は競争が激しすぎて、みんな遅くまで残業してる。"] },
  { zh: "摆烂", pinyin: "bǎilàn", title: "どうにでもなれと投げ出す", art: "🫠📉", explain: "うまくいかないと分かって、開き直って努力をやめること。", ex: ["明天就考试了，我已经摆烂了。", "Míngtiān jiù kǎoshì le, wǒ yǐjīng bǎilàn le.", "明日はもう試験だけど、完全に開き直ってる。"] },
  { zh: "打工人", pinyin: "dǎgōngrén", title: "働く人(自虐を込めて)", art: "🧑‍💻☕", explain: "会社員など雇われて働く人のこと。「お疲れ、社畜仲間」のような自虐的なあいさつに使う。", ex: ["早安，打工人！", "Zǎo'ān, dǎgōngrén!", "おはよう、働く者たちよ!"] },
  { zh: "吃瓜", pinyin: "chīguā", title: "野次馬として見物する", art: "🍉👀", explain: "瓜(スイカの種)を食べながら騒ぎを眺める様子から。噂話やゴシップを見物する人は「吃瓜群众」。", ex: ["我只是来吃瓜的。", "Wǒ zhǐshì lái chīguā de.", "私はただ見物に来ただけ。"] },
  { zh: "社恐", pinyin: "shèkǒng", title: "人付き合いが苦手", art: "🙈💦", explain: "「社交恐惧症」の略。知らない人と話すのが苦手なことを軽く言う。", ex: ["我是社恐，不太喜欢参加聚会。", "Wǒ shì shèkǒng, bú tài xǐhuan cānjiā jùhuì.", "私は人見知りだから、飲み会はあまり好きじゃない。"] },
  { zh: "凡尔赛", pinyin: "fán'ěrsài", title: "さりげない自慢", art: "👑💅", explain: "「ヴェルサイユ(宮殿)」の意味。謙遜や愚痴に見せかけて自慢すること。", ex: ["别凡尔赛了，谁不知道你很有钱。", "Bié fán'ěrsài le, shéi bù zhīdào nǐ hěn yǒu qián.", "さりげない自慢はやめて、お金持ちなのはみんな知ってるよ。"] },
  { zh: "破防", pinyin: "pòfáng", title: "心の防御が崩れる", art: "🥹💔", explain: "ゲームの「防御を破る」から。感動や衝撃で気持ちがこらえきれなくなること。", ex: ["看到这个视频，我直接破防了。", "Kàndào zhège shìpín, wǒ zhíjiē pòfáng le.", "この動画を見て、一気に涙腺が崩壊した。"] },
  { zh: "种草", pinyin: "zhòngcǎo", title: "欲しくなる", art: "🌱🛒", explain: "「草を植える」=人のおすすめで物欲が芽生えること。逆に実際に買う・行くことは「拔草」。", ex: ["她推荐的口红让我种草了。", "Tā tuījiàn de kǒuhóng ràng wǒ zhòngcǎo le.", "彼女がすすめてた口紅、欲しくなっちゃった。"] },
  { zh: "佛系", pinyin: "fóxì", title: "欲がなく自然体", art: "🧘✨", explain: "仏のように、こだわらず争わず、なりゆきに任せるスタイル。", ex: ["他对工作很佛系。", "Tā duì gōngzuò hěn fóxì.", "彼は仕事にガツガツしていない。"] },
  { zh: "学霸", pinyin: "xuébà", title: "勉強ができる人", art: "📚🏆", explain: "成績がずば抜けて良い人。反対に勉強が苦手な人は「学渣 xuézhā」。", ex: ["她是我们班的学霸。", "Tā shì wǒmen bān de xuébà.", "彼女はうちのクラスの秀才だ。"] },
  { zh: "网红", pinyin: "wǎnghóng", title: "インフルエンサー・映えスポット", art: "📸🔥", explain: "「网络红人」の略。ネットで人気の人、または話題の店や場所。", ex: ["这是一家网红咖啡店。", "Zhè shì yì jiā wǎnghóng kāfēidiàn.", "ここはSNSで話題のカフェだ。"] },
  { zh: "打卡", pinyin: "dǎkǎ", title: "行ってきた記録をする", art: "📍📱", explain: "もとは出勤の打刻。人気スポットに行って写真をSNSに上げることにも使う。", ex: ["周末我们去那家网红店打卡吧。", "Zhōumò wǒmen qù nà jiā wǎnghóng diàn dǎkǎ ba.", "週末、あの話題のお店に行ってみようよ。"] },
  { zh: "硬核", pinyin: "yìnghé", title: "本格的・すごい", art: "💪🔩", explain: "英語の hardcore から。筋金入りでかっこいい、ガチな、という意味。", ex: ["这位老奶奶太硬核了！", "Zhè wèi lǎonǎinai tài yìnghé le!", "このおばあちゃん、すごすぎる!"] },
  { zh: "永远的神", pinyin: "yǒngyuǎn de shén", title: "最強・神(YYDS)", art: "🔥🙌", explain: "「永遠の神」。最高のものをほめる言葉で、ピンインの頭文字から YYDS とも書く。", ex: ["火锅永远的神！", "Huǒguō yǒngyuǎn de shén!", "火鍋こそ最強!"] },
];

// ネイティブ表現(会話でよく使う言い回し)
const NATIVE_EXPRESSIONS = [
  { zh: "没事儿", pinyin: "méi shìr", title: "大丈夫・気にしないで", art: "🙆", explain: "謝られた時やお礼を言われた時の返事に。北方ではよく「儿」を付けて言う。", ex: ["A：对不起，我来晚了。B：没事儿。", "A: Duìbuqǐ, wǒ lái wǎn le. B: Méi shìr.", "A: ごめん、遅くなった。B: 気にしないで。"] },
  { zh: "随便", pinyin: "suíbiàn", title: "何でもいいよ・ご自由に", art: "🤷", explain: "相手に任せる時に。ただし言い方によっては投げやりに聞こえるので注意。", ex: ["你想吃什么？——随便。", "Nǐ xiǎng chī shénme? —— Suíbiàn.", "何食べたい?——何でもいいよ。"] },
  { zh: "加油", pinyin: "jiāyóu", title: "がんばって", art: "💪", explain: "直訳は「油を足す」。応援するときの定番。", ex: ["明天考试，加油！", "Míngtiān kǎoshì, jiāyóu!", "明日の試験、がんばって!"] },
  { zh: "辛苦了", pinyin: "xīnkǔ le", title: "お疲れさま", art: "🙇", explain: "相手の苦労をねぎらう言葉。目上の人にも使える。", ex: ["今天大家辛苦了！", "Jīntiān dàjiā xīnkǔ le!", "今日はみなさんお疲れさまでした!"] },
  { zh: "慢走", pinyin: "màn zǒu", title: "お気をつけて(見送り)", art: "👋", explain: "お客さんを見送る時の決まり文句。「ゆっくり歩いて」が直訳。", ex: ["谢谢光临，您慢走！", "Xièxie guānglín, nín màn zǒu!", "ご来店ありがとうございました、お気をつけて!"] },
  { zh: "不好意思", pinyin: "bù hǎoyìsi", title: "すみません", art: "🙏", explain: "軽い謝罪、呼びかけ、恐縮する気持ちなど、日本語の「すみません」に近い万能表現。", ex: ["不好意思，请问地铁站在哪儿？", "Bù hǎoyìsi, qǐngwèn dìtiě zhàn zài nǎr?", "すみません、地下鉄の駅はどこですか?"] },
  { zh: "真的假的", pinyin: "zhēn de jiǎ de", title: "マジで?", art: "😲", explain: "「本当?嘘?」と驚いた時の口語表現。", ex: ["他辞职了？真的假的？", "Tā cízhí le? Zhēn de jiǎ de?", "彼が辞めた?マジで?"] },
  { zh: "算了", pinyin: "suàn le", title: "もういいや・やめとこう", art: "😮‍💨", explain: "あきらめる時や、話を打ち切る時に。", ex: ["算了，我们明天再说吧。", "Suàn le, wǒmen míngtiān zài shuō ba.", "もういいや、明日また話そう。"] },
  { zh: "改天吧", pinyin: "gǎitiān ba", title: "また今度にしよう", art: "📅", explain: "誘いをやんわり断る時や、日を改める時に。", ex: ["今天有点儿忙，改天吧。", "Jīntiān yǒudiǎnr máng, gǎitiān ba.", "今日はちょっと忙しいから、また今度にしよう。"] },
  { zh: "我请客", pinyin: "wǒ qǐngkè", title: "私がおごるよ", art: "💴", explain: "食事の会計の時に。中国では誰がおごるかで押し問答になることも。", ex: ["今天我请客，别客气！", "Jīntiān wǒ qǐngkè, bié kèqi!", "今日は私のおごり、遠慮しないで!"] },
  { zh: "太夸张了", pinyin: "tài kuāzhāng le", title: "大げさすぎ・ありえない", art: "🤯", explain: "話が大げさな時や、程度がすごすぎる時の反応に。", ex: ["排队要三个小时？太夸张了！", "Páiduì yào sān ge xiǎoshí? Tài kuāzhāng le!", "3時間並ぶの?ありえない!"] },
  { zh: "靠谱", pinyin: "kàopǔ", title: "信頼できる・ちゃんとしてる", art: "👍", explain: "人や計画が確かで頼れること。反対は「不靠谱」。", ex: ["他做事很靠谱。", "Tā zuò shì hěn kàopǔ.", "彼は仕事がきっちりしていて信頼できる。"] },
  { zh: "搞定", pinyin: "gǎodìng", title: "片付いた・なんとかした", art: "✅", explain: "問題や仕事をやり遂げたときに。「任せて、何とかする」の意味にも。", ex: ["报告我已经搞定了。", "Bàogào wǒ yǐjīng gǎodìng le.", "報告書はもう片付けたよ。"] },
  { zh: "没办法", pinyin: "méi bànfǎ", title: "仕方ない", art: "🤲", explain: "どうしようもない状況で。「没办法，只能这样了」のように使う。", ex: ["下雨了，没办法，我们改天去吧。", "Xià yǔ le, méi bànfǎ, wǒmen gǎitiān qù ba.", "雨が降ってきた、仕方ないから別の日に行こう。"] },
  { zh: "哪里哪里", pinyin: "nǎli nǎli", title: "いえいえ(謙遜)", art: "😊", explain: "ほめられた時の謙遜の定番。最近は「谢谢」と素直に受ける人も多い。", ex: ["你的中文说得真好！——哪里哪里。", "Nǐ de Zhōngwén shuō de zhēn hǎo! —— Nǎli nǎli.", "中国語お上手ですね!——いえいえ、とんでもない。"] },
];
