// 練習タブ・トークタブの AI 会話で使う題材

const SCENARIO_CATEGORIES = [
  { id: "all", label: "全部" },
  { id: "social", label: "ソーシャル" },
  { id: "life", label: "生活" },
  { id: "work", label: "職場" },
  { id: "travel", label: "旅行" },
];

const SCENARIO_LEVELS = [
  { id: "all", label: "全部" },
  { id: "beginner", label: "初級" },
  { id: "intermediate", label: "中級" },
  { id: "advanced", label: "上級" },
];

// role: AI が演じる役 / situation: 学習者に見せる状況説明 / goal: 会話のゴール
const SCENARIOS = [
  {
    id: "new-friend",
    title: "新しい友達に出会う",
    category: "social",
    level: "beginner",
    icon: "🥂",
    situation: "友人の小美が主催するパーティーに参加しています。初対面の人に話しかけられました。",
    role: "パーティーに来ている中国人の会社員「阿明」。明るく気さくで、初対面の相手に名前・出身・仕事などを尋ねる。",
    goal: "自己紹介をして、相手の名前と仕事を聞き、連絡先(WeChat)を交換する",
  },
  {
    id: "birthday",
    title: "友達の誕生日を祝う",
    category: "social",
    level: "beginner",
    icon: "🎂",
    situation: "中国人の友達・小美の誕生日です。お祝いのメッセージを伝えてプレゼントを渡します。",
    role: "誕生日を迎えた友人「小美」。プレゼントをもらって喜び、お礼を言う。",
    goal: "誕生日のお祝いを言い、プレゼントを渡して、一緒にケーキを食べようと誘う",
  },
  {
    id: "hobby",
    title: "趣味について話す",
    category: "social",
    level: "intermediate",
    icon: "🎨",
    situation: "語学交換で知り合った中国人と、お互いの趣味について話しています。",
    role: "語学交換パートナーの「李静」。写真と旅行が趣味で、相手の趣味にも興味津々。",
    goal: "自分の趣味を説明し、いつから・なぜ好きかを話し、相手の趣味についても質問する",
  },
  {
    id: "invite-dinner",
    title: "友達を食事に誘う",
    category: "social",
    level: "intermediate",
    icon: "🍲",
    situation: "中国人の同僚と仲良くなってきたので、週末の食事に誘います。",
    role: "同僚の「王磊」。火鍋が大好き。週末は土曜が忙しく日曜なら空いている。",
    goal: "食事に誘い、日時・お店・待ち合わせ場所を決める",
  },
  {
    id: "restaurant",
    title: "レストランで注文する",
    category: "life",
    level: "beginner",
    icon: "🍜",
    situation: "北京の中華料理店に入りました。店員さんが注文を取りに来ます。",
    role: "レストランの店員。おすすめは北京ダック(烤鸭)と宮保鶏丁(宫保鸡丁)。辛さの好みや飲み物も確認する。",
    goal: "おすすめを聞いて料理2品と飲み物を注文し、最後に会計をする",
  },
  {
    id: "supermarket",
    title: "スーパーで買い物",
    category: "life",
    level: "beginner",
    icon: "🛒",
    situation: "上海のスーパーで、探している商品が見つかりません。",
    role: "スーパーの店員。売り場の場所を案内し、値段やセールの情報を教える。支払いは現金・WeChat Pay・Alipay が使える。",
    goal: "牛乳と果物の売り場を聞き、値段を確認して、支払い方法を尋ねる",
  },
  {
    id: "taxi",
    title: "タクシーに乗る",
    category: "life",
    level: "beginner",
    icon: "🚕",
    situation: "空港からタクシーでホテルに向かいます。",
    role: "タクシーの運転手。気さくで、行き先・所要時間・道の混み具合などを話す。",
    goal: "行き先を伝え、所要時間と料金の目安を聞き、到着したら領収書(发票)をもらう",
  },
  {
    id: "clinic",
    title: "病院で症状を伝える",
    category: "life",
    level: "intermediate",
    icon: "🏥",
    situation: "昨日から熱と喉の痛みがあり、病院に来ました。",
    role: "内科の医師。症状・いつから・熱の高さ・アレルギーの有無を順に質問し、薬の飲み方を説明する。",
    goal: "症状といつからかを説明し、薬の飲み方を確認する",
  },
  {
    id: "rent",
    title: "部屋を借りる",
    category: "life",
    level: "advanced",
    icon: "🏠",
    situation: "中国で駐在することになり、不動産屋で部屋を探しています。",
    role: "不動産会社の担当者。家賃・広さ・駅からの距離・契約期間・敷金(押金)について説明し、交渉にも応じる。",
    goal: "希望条件を伝え、家賃と契約条件を確認し、家賃の値下げを交渉する",
  },
  {
    id: "interview",
    title: "面接",
    category: "work",
    level: "advanced",
    icon: "💼",
    situation: "中国企業の面接を受けています。面接官が質問します。",
    role: "中国企業の人事部の面接官。自己紹介・志望動機・強み・日本での経験・入社可能時期を質問する。丁寧だが鋭い質問もする。",
    goal: "自己紹介・志望動機・自分の強みを説明し、最後に質問を1つする",
  },
  {
    id: "first-day",
    title: "出社初日のあいさつ",
    category: "work",
    level: "intermediate",
    icon: "👋",
    situation: "中国の支社に着任した初日です。チームの同僚に自己紹介します。",
    role: "チームリーダーの「张经理」。歓迎し、チームの仕事内容や分からないことがあれば聞くよう伝える。",
    goal: "自己紹介をして、担当業務と今日の予定を確認する",
  },
  {
    id: "meeting",
    title: "会議で意見を言う",
    category: "work",
    level: "advanced",
    icon: "📊",
    situation: "新商品の販売戦略の会議中です。意見を求められました。",
    role: "マーケティング部長。SNS広告に予算を集中すべきだと考えているが、根拠のある反対意見には耳を傾ける。",
    goal: "賛成・反対の立場と理由を述べ、具体的な提案をする",
  },
  {
    id: "phone-client",
    title: "取引先に電話する",
    category: "work",
    level: "intermediate",
    icon: "📞",
    situation: "取引先の王さんに、来週の打ち合わせの日程調整の電話をかけます。",
    role: "取引先の受付→王経理本人。王さんは来週火曜の午後と木曜の午前なら空いている。",
    goal: "王さんに取り次いでもらい、打ち合わせの日時と場所を決める",
  },
  {
    id: "deadline",
    title: "納期を交渉する",
    category: "work",
    level: "advanced",
    icon: "⏰",
    situation: "取引先から納期の前倒しを依頼されましたが、そのままでは難しい状況です。",
    role: "取引先の購買担当「刘总」。納期を1週間早めてほしいと強く求めるが、代替案(分納・追加費用など)には応じる。",
    goal: "事情を説明し、分納などの代替案を提案して合意する",
  },
  {
    id: "train-ticket",
    title: "汽車の切符を買う",
    category: "travel",
    level: "intermediate",
    icon: "🚄",
    situation: "友達と一緒に上海から杭州への高速鉄道の切符を買います。",
    role: "駅の切符売り場の係員。便の時刻・座席の等級(二等座/一等座)・料金を案内し、パスポートの提示を求める。",
    goal: "明日の午前の便を2人分、隣同士の席で買う",
  },
  {
    id: "hotel",
    title: "ホテルにチェックイン",
    category: "travel",
    level: "beginner",
    icon: "🏨",
    situation: "予約していたホテルに到着しました。",
    role: "ホテルのフロント係。予約確認・パスポート・デポジット(押金)・朝食の時間・Wi-Fiを案内する。",
    goal: "チェックインして、朝食の時間とWi-Fiのパスワードを聞く",
  },
  {
    id: "directions",
    title: "道を尋ねる",
    category: "travel",
    level: "beginner",
    icon: "🗺️",
    situation: "西安の街中で、有名な観光地への行き方が分かりません。",
    role: "親切な通行人。鐘楼(钟楼)までの行き方(地下鉄・徒歩)と時間を教える。",
    goal: "目的地への行き方と時間を聞いて、お礼を言う",
  },
  {
    id: "airport",
    title: "空港で搭乗手続き",
    category: "travel",
    level: "intermediate",
    icon: "✈️",
    situation: "北京首都空港で東京行きの便の搭乗手続きをします。",
    role: "航空会社のカウンター係員。パスポート確認・座席の希望・預け荷物・搭乗口と時刻を案内する。",
    goal: "窓側の席を希望し、荷物を預けて、搭乗口と搭乗時刻を確認する",
  },
  {
    id: "souvenir",
    title: "お土産を値切る",
    category: "travel",
    level: "intermediate",
    icon: "🛍️",
    situation: "北京の市場でお土産を選んでいます。",
    role: "市場の店主。最初は高めの値段を言うが、まとめ買いや交渉で少し安くする。",
    goal: "商品の値段を聞き、まとめ買いで値引き交渉して買う",
  },
];

// 絵を見て話す: 画像の代わりに絵文字で場面を表す
const PICTURE_SCENES = [
  { id: "dinner", art: "👨‍👩‍👧 🍲 🏠", title: "家族で夕ごはん", scene: "夜、家で家族3人(父・母・娘)が火鍋を囲んで楽しそうに食事をしている" },
  { id: "park", art: "🌳 🐕 🚶‍♀️ ☀️", title: "公園で散歩", scene: "晴れた日の公園で、女性が犬を連れて散歩している" },
  { id: "rain", art: "🌧️ 🚉 ☂️ 🧍", title: "雨の日の駅", scene: "雨の日、駅の出口で傘を持っていない人が雨がやむのを待っている" },
  { id: "cafe", art: "☕ 📚 💻 🧑‍🎓", title: "カフェで勉強", scene: "学生がカフェでコーヒーを飲みながらパソコンと本で勉強している" },
  { id: "birthday", art: "🎂 🎈 🎉 👫", title: "誕生日パーティー", scene: "友達同士で誕生日パーティーをしていて、ケーキと風船がある" },
  { id: "beach", art: "🏖️ 🌊 ☀️ 🍉", title: "夏の海", scene: "夏の暑い日に海辺で泳いだりスイカを食べたりしている" },
  { id: "office", art: "🧑‍💼 📊 👩‍💼 🗓️", title: "オフィスで会議", scene: "会社の会議室で、グラフを見ながら社員たちが会議をしている" },
  { id: "market", art: "🛒 🍎 🥛 🧾", title: "スーパーで買い物", scene: "スーパーでカートを押しながら果物と牛乳を買っている" },
  { id: "snow", art: "❄️ ⛄ 🧣 👧", title: "雪の日", scene: "雪が積もった日に、マフラーを巻いた子どもが雪だるまを作っている" },
  { id: "airport", art: "✈️ 🧳 🕐 🙋", title: "空港で", scene: "空港でスーツケースを持った人が搭乗時刻を気にしている" },
  { id: "cooking", art: "🍳 🥕 🔪 👨‍🍳", title: "料理をする", scene: "キッチンで男性が野菜を切って料理を作っている" },
  { id: "cinema", art: "🎬 🍿 🎟️ 👩‍❤️‍👨", title: "映画館", scene: "カップルが映画館でポップコーンを持って映画を見ている" },
];

// トーク: AI の友達と話す話題
const TALK_TOPICS = [
  { id: "hobby", icon: "🎨", title: "趣味", opener: "お互いの趣味" },
  { id: "food", icon: "🍜", title: "食べ物", opener: "好きな食べ物・料理" },
  { id: "travel", icon: "✈️", title: "旅行", opener: "行ったことのある場所・行きたい場所" },
  { id: "work", icon: "💼", title: "仕事", opener: "仕事や職場のこと" },
  { id: "movie", icon: "🎬", title: "映画・ドラマ", opener: "最近見た映画やドラマ" },
  { id: "weekend", icon: "📅", title: "週末の予定", opener: "週末に何をするか" },
  { id: "culture", icon: "🇯🇵", title: "日本と中国の違い", opener: "日本と中国の文化・習慣の違い" },
  { id: "recent", icon: "✨", title: "最近ハマっていること", opener: "最近ハマっていること" },
];

const TALK_PARTNERS = [
  {
    id: "xiaomei",
    name: "小美",
    avatar: "🌸",
    profile: "上海のIT企業で働く28歳の会社員「小美」。明るくおしゃべりで、タピオカと旅行が好き。日本のアニメにも詳しい。",
  },
  {
    id: "aming",
    name: "阿明",
    avatar: "🎓",
    profile: "北京の大学に通う21歳の学生「阿明」。バスケとゲームが好きで、日本に留学したいと思っている。",
  },
];
