// 追加ユニット第2弾(u21〜u32)。ロードマップを細かく区切るのに合わせて、
// 各段階の間を埋める日常・ビジネスのユニットを追加する。並び順とレベルは curriculum.js で決める。

(() => {
  const L = (audioText, pinyin, correct, ...wrong) => ({
    type: "listening_choice",
    audioText,
    pinyin,
    prompt: "今聞こえた文の意味はどれ?",
    choices: [{ text: correct, correct: true }, ...wrong.map((text) => ({ text, correct: false }))],
  });
  const T = (hanzi, pinyin, correct, ...wrong) => ({
    type: "translate_choice",
    hanzi,
    pinyin,
    prompt: "この文の意味は?",
    choices: [{ text: correct, correct: true }, ...wrong.map((text) => ({ text, correct: false }))],
  });
  const S = (hanzi, pinyin, meaning) => ({ type: "speaking", hanzi, pinyin, meaning, prompt: "声に出して発音してみましょう" });
  const W = (meaning, pinyinHint, answer) => ({ type: "writing_cn", meaning, pinyinHint, answer });
  const strip = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
  const P = (hanzi, meaningHint, answerToned) => ({ type: "writing_pinyin", hanzi, meaningHint, answer: strip(answerToned), answerToned });
  const R = (passage, passagePinyin, question, correct, ...wrong) => ({
    type: "reading",
    passage,
    passagePinyin,
    question,
    choices: [{ text: correct, correct: true }, ...wrong.map((text) => ({ text, correct: false }))],
  });

  const UNITS2 = [
    {
      id: "u21",
      title: "食べ物と飲み物",
      description: "飲み物や料理を頼む・味を伝える・会計する",
      icon: "🍜",
      lessons: [
        {
          id: "u21l1",
          title: "飲み物を頼む",
          exercises: [
            L("你想喝什么", "nǐ xiǎng hē shénme", "何を飲みたいですか?", "何を食べたいですか?", "何を買いたいですか?"),
            T("我要一杯咖啡", "wǒ yào yì bēi kāfēi", "コーヒーを1杯ください", "お茶を1杯ください", "水を1本ください"),
            S("我要一杯茶", "wǒ yào yì bēi chá", "お茶を1杯ください"),
            W("水", "shuǐ", "水"),
            L("请给我一瓶水", "qǐng gěi wǒ yì píng shuǐ", "水を1本ください", "水を1杯ください", "お湯をください"),
            R("我每天早上喝一杯咖啡,下午喝茶。", "Wǒ měitiān zǎoshang hē yì bēi kāfēi, xiàwǔ hē chá.", "この人は午後に何を飲みますか?", "お茶", "コーヒー", "水"),
            P("喝", "飲む", "hē"),
          ],
        },
        {
          id: "u21l2",
          title: "食事をする",
          exercises: [
            L("我饿了", "wǒ è le", "おなかがすきました", "のどが渇きました", "おなかがいっぱいです"),
            T("我们去吃饺子吧", "wǒmen qù chī jiǎozi ba", "餃子を食べに行きましょう", "餃子を作りましょう", "餃子を買いましょう"),
            S("这个菜很好吃", "zhège cài hěn hǎochī", "この料理はとてもおいしいです"),
            W("ご飯(炊いたお米)", "mǐfàn", "米饭"),
            L("我吃饱了", "wǒ chī bǎo le", "おなかいっぱいです", "まだ食べていません", "もっと食べたいです"),
            R("中午我和同事一起去吃面条。面条很好吃,也不贵。", "Zhōngwǔ wǒ hé tóngshì yìqǐ qù chī miàntiáo. Miàntiáo hěn hǎochī, yě bú guì.", "お昼に何を食べましたか?", "麺", "餃子", "ご飯"),
            P("好吃", "おいしい", "hǎochī"),
          ],
        },
        {
          id: "u21l3",
          title: "注文と会計",
          exercises: [
            L("服务员,我们要点菜", "fúwùyuán, wǒmen yào diǎn cài", "すみません、注文をお願いします", "すみません、お会計をお願いします", "すみません、メニューはありますか"),
            T("不要放香菜", "bú yào fàng xiāngcài", "パクチーは入れないでください", "パクチーを多めにしてください", "パクチーはありますか"),
            S("服务员,买单", "fúwùyuán, mǎidān", "すみません、お会計をお願いします"),
            W("辛い", "là", "辣"),
            L("这个菜太辣了", "zhège cài tài là le", "この料理は辛すぎます", "この料理は甘すぎます", "この料理は冷めています"),
            R("我点了一个宫保鸡丁和一碗米饭,一共五十八块。", "Wǒ diǎn le yí ge gōngbǎo jīdīng hé yì wǎn mǐfàn, yígòng wǔshíbā kuài.", "合計はいくらでしたか?", "58元", "85元", "50元"),
            P("菜单", "メニュー", "càidān"),
          ],
        },
      ],
    },
    {
      id: "u22",
      title: "天気と季節",
      description: "天気を聞く・季節の話・天気予報",
      icon: "🌤️",
      lessons: [
        {
          id: "u22l1",
          title: "今日の天気",
          exercises: [
            L("今天天气怎么样", "jīntiān tiānqì zěnmeyàng", "今日の天気はどうですか?", "明日の天気はどうですか?", "今日は何曜日ですか?"),
            T("外面下雨了", "wàimiàn xià yǔ le", "外は雨が降ってきました", "外は雪が降っています", "外は晴れています"),
            S("今天很热", "jīntiān hěn rè", "今日はとても暑いです"),
            W("傘", "sǎn", "伞"),
            L("出门别忘了带伞", "chūmén bié wàng le dài sǎn", "出かけるときに傘を忘れないで", "出かけるときに鍵を忘れないで", "傘をなくしました"),
            R("今天是晴天,不冷也不热。我们去公园散步吧。", "Jīntiān shì qíngtiān, bù lěng yě bú rè. Wǒmen qù gōngyuán sànbù ba.", "今日の天気は?", "晴れで暑くも寒くもない", "雨で寒い", "曇りで暑い"),
            P("天气", "天気", "tiānqì"),
          ],
        },
        {
          id: "u22l2",
          title: "季節",
          exercises: [
            L("我最喜欢秋天", "wǒ zuì xǐhuan qiūtiān", "私は秋が一番好きです", "私は春が一番好きです", "私は秋が苦手です"),
            T("北京的冬天很冷", "Běijīng de dōngtiān hěn lěng", "北京の冬はとても寒いです", "北京の夏はとても暑いです", "北京の冬は暖かいです"),
            S("上海的夏天又热又湿", "Shànghǎi de xiàtiān yòu rè yòu shī", "上海の夏は暑くてじめじめしています"),
            W("春", "chūntiān", "春天"),
            L("春天到了,花都开了", "chūntiān dào le, huā dōu kāi le", "春が来て、花がみんな咲きました", "冬が来て、雪が降りました", "春なのにまだ寒いです"),
            R("日本有四个季节。春天可以看樱花,秋天的红叶也很漂亮。", "Rìběn yǒu sì ge jìjié. Chūntiān kěyǐ kàn yīnghuā, qiūtiān de hóngyè yě hěn piàoliang.", "春に見られるものは?", "桜", "紅葉", "雪"),
            P("季节", "季節", "jìjié"),
          ],
        },
        {
          id: "u22l3",
          title: "天気予報",
          exercises: [
            L("天气预报说明天有雨", "tiānqì yùbào shuō míngtiān yǒu yǔ", "天気予報によると明日は雨です", "天気予報によると明日は晴れです", "明日の天気予報はまだ出ていません"),
            T("今天最高气温三十五度", "jīntiān zuì gāo qìwēn sānshíwǔ dù", "今日の最高気温は35度です", "今日の最低気温は35度です", "今日は35度まで下がります"),
            S("听说周末有台风", "tīngshuō zhōumò yǒu táifēng", "週末は台風が来るそうです"),
            W("気温", "qìwēn", "气温"),
            L("航班因为大雾取消了", "hángbān yīnwèi dà wù qǔxiāo le", "濃霧のためフライトが欠航になりました", "大雨のためフライトが遅れました", "フライトは予定どおりです"),
            R("受台风影响,明天上海有大风和暴雨,请大家尽量不要出门。", "Shòu táifēng yǐngxiǎng, míngtiān Shànghǎi yǒu dà fēng hé bàoyǔ, qǐng dàjiā jǐnliàng bú yào chūmén.", "明日はどうするよう呼びかけていますか?", "なるべく外出しない", "早めに出勤する", "傘を買っておく"),
            P("台风", "台風", "táifēng"),
          ],
        },
      ],
    },
    {
      id: "u23",
      title: "趣味と週末",
      description: "趣味の話・週末の予定・誘う/断る",
      icon: "🎨",
      lessons: [
        {
          id: "u23l1",
          title: "趣味を話す",
          exercises: [
            L("你的爱好是什么", "nǐ de àihào shì shénme", "あなたの趣味は何ですか?", "あなたの仕事は何ですか?", "あなたの名前は何ですか?"),
            T("我喜欢看电影", "wǒ xǐhuan kàn diànyǐng", "映画を見るのが好きです", "本を読むのが好きです", "音楽を聞くのが好きです"),
            S("我的爱好是跑步", "wǒ de àihào shì pǎobù", "私の趣味はジョギングです"),
            W("趣味", "àihào", "爱好"),
            L("我每个星期打两次网球", "wǒ měi ge xīngqī dǎ liǎng cì wǎngqiú", "毎週2回テニスをします", "毎週2回ゴルフをします", "2週間に1回テニスをします"),
            R("我喜欢做饭,周末常常在家做中国菜。我最拿手的是麻婆豆腐。", "Wǒ xǐhuan zuòfàn, zhōumò chángcháng zài jiā zuò Zhōngguó cài. Wǒ zuì náshǒu de shì mápó dòufu.", "この人の得意料理は?", "麻婆豆腐", "餃子", "チャーハン"),
            P("运动", "運動・スポーツ", "yùndòng"),
          ],
        },
        {
          id: "u23l2",
          title: "週末の予定",
          exercises: [
            L("周末你打算做什么", "zhōumò nǐ dǎsuàn zuò shénme", "週末は何をするつもりですか?", "週末は何をしましたか?", "週末は忙しいですか?"),
            T("我打算和朋友去爬山", "wǒ dǎsuàn hé péngyou qù pá shān", "友達と山登りに行くつもりです", "友達と海に行きました", "一人で山に行きたいです"),
            S("这个周末我想在家休息", "zhège zhōumò wǒ xiǎng zài jiā xiūxi", "今週末は家で休みたいです"),
            W("週末", "zhōumò", "周末"),
            L("上个周末你去哪儿了", "shàng ge zhōumò nǐ qù nǎr le", "先週末はどこに行きましたか?", "来週末はどこに行きますか?", "週末はいつも何をしますか?"),
            R("上周六我去了外滩,晚上的风景特别漂亮。周日在家看了一部电影。", "Shàng zhōuliù wǒ qù le Wàitān, wǎnshang de fēngjǐng tèbié piàoliang. Zhōurì zài jiā kàn le yí bù diànyǐng.", "日曜日には何をしましたか?", "家で映画を見た", "外灘に行った", "買い物をした"),
            P("打算", "〜するつもり", "dǎsuàn"),
          ],
        },
        {
          id: "u23l3",
          title: "誘う・断る",
          exercises: [
            L("今天晚上一起去喝一杯吧", "jīntiān wǎnshang yìqǐ qù hē yì bēi ba", "今夜一緒に一杯飲みに行きましょう", "今夜は早く帰りましょう", "今夜は残業しましょう"),
            T("不好意思,今天我有点事", "bù hǎoyìsi, jīntiān wǒ yǒudiǎn shì", "すみません、今日はちょっと用事があります", "すみません、今日は大丈夫です", "すみません、遅れました"),
            S("太好了,我一定去", "tài hǎo le, wǒ yídìng qù", "いいですね、必ず行きます"),
            W("誘う・招待する", "yāoqǐng", "邀请"),
            L("那我们下次再约吧", "nà wǒmen xià cì zài yuē ba", "では、また今度約束しましょう", "では、明日にしましょう", "では、今から行きましょう"),
            R("小李约我周五晚上去唱歌,可是我那天要加班,所以只好拒绝了。", "Xiǎo Lǐ yuē wǒ zhōuwǔ wǎnshang qù chàng gē, kěshì wǒ nà tiān yào jiābān, suǒyǐ zhǐhǎo jùjué le.", "なぜ誘いを断りましたか?", "残業があるから", "歌が苦手だから", "体調が悪いから"),
            P("下次", "次回", "xià cì"),
          ],
        },
      ],
    },
    {
      id: "u24",
      title: "体調と病院",
      description: "体調を伝える・病院で・休みの連絡",
      icon: "🏥",
      lessons: [
        {
          id: "u24l1",
          title: "体調を伝える",
          exercises: [
            L("我有点不舒服", "wǒ yǒudiǎn bù shūfu", "少し気分が悪いです", "とても元気です", "少し疲れました"),
            T("我头疼,还有点发烧", "wǒ tóu téng, hái yǒudiǎn fāshāo", "頭が痛くて、少し熱もあります", "おなかが痛くて、吐き気があります", "のどが痛くて、咳が出ます"),
            S("我好像感冒了", "wǒ hǎoxiàng gǎnmào le", "風邪をひいたみたいです"),
            W("頭が痛い", "tóu téng", "头疼"),
            L("你脸色不太好,没事吧", "nǐ liǎnsè bú tài hǎo, méi shì ba", "顔色があまりよくないけど、大丈夫?", "顔色がいいですね", "今日は元気そうですね"),
            R("昨天晚上我吃了很多海鲜,今天早上肚子很疼,可能是吃坏了。", "Zuótiān wǎnshang wǒ chī le hěn duō hǎixiān, jīntiān zǎoshang dùzi hěn téng, kěnéng shì chī huài le.", "おなかが痛い原因は何だと思っていますか?", "昨夜食べた海鮮", "冷たい飲み物", "寝不足"),
            P("舒服", "気持ちがよい・体調がよい", "shūfu"),
          ],
        },
        {
          id: "u24l2",
          title: "病院で",
          exercises: [
            L("请先去挂号", "qǐng xiān qù guàhào", "まず受付をしてください", "まず薬を受け取ってください", "まず会計をしてください"),
            T("这个药一天吃三次", "zhège yào yì tiān chī sān cì", "この薬は1日3回飲みます", "この薬は3日に1回飲みます", "この薬は食前に飲みます"),
            S("医生,我咳嗽得很厉害", "yīshēng, wǒ késou de hěn lìhai", "先生、咳がひどいんです"),
            W("薬", "yào", "药"),
            L("你需要验一下血", "nǐ xūyào yàn yíxià xiě", "血液検査が必要です", "注射が必要です", "入院が必要です"),
            R("医生说我是普通感冒,不用打针。给我开了三天的药,让我多喝水、多休息。", "Yīshēng shuō wǒ shì pǔtōng gǎnmào, bú yòng dǎzhēn. Gěi wǒ kāi le sān tiān de yào, ràng wǒ duō hē shuǐ, duō xiūxi.", "医者の指示は?", "水をたくさん飲んでよく休む", "すぐ注射をする", "明日また来る"),
            P("医院", "病院", "yīyuàn"),
          ],
        },
        {
          id: "u24l3",
          title: "休みの連絡",
          exercises: [
            L("我今天身体不舒服,想请一天假", "wǒ jīntiān shēntǐ bù shūfu, xiǎng qǐng yì tiān jià", "今日は体調が悪いので、1日休みをもらいたいです", "今日は午後から出社します", "今日は在宅勤務にします"),
            T("好好休息,工作的事不用担心", "hǎohǎo xiūxi, gōngzuò de shì bú yòng dānxīn", "しっかり休んで、仕事のことは心配しないで", "早く会社に戻ってきて", "仕事は家でやってください"),
            S("祝你早日康复", "zhù nǐ zǎorì kāngfù", "早く良くなりますように"),
            W("休暇を取る", "qǐngjià", "请假"),
            L("明天的会议我可能参加不了", "míngtiān de huìyì wǒ kěnéng cānjiā bu liǎo", "明日の会議には出られないかもしれません", "明日の会議には必ず出ます", "明日の会議は中止です"),
            R("王经理:我今天发烧了,需要在家休息。下午的会请小张代我参加,资料已经发到群里了。", "Wáng jīnglǐ: Wǒ jīntiān fāshāo le, xūyào zài jiā xiūxi. Xiàwǔ de huì qǐng Xiǎo Zhāng dài wǒ cānjiā, zīliào yǐjīng fā dào qún li le.", "午後の会議には誰が代わりに出ますか?", "張さん", "王マネージャー", "誰も出ない"),
            P("康复", "回復する", "kāngfù"),
          ],
        },
      ],
    },
    {
      id: "u25",
      title: "オフィスでの一日",
      description: "出社・仕事を頼む/引き受ける・退勤と残業",
      icon: "🏢",
      lessons: [
        {
          id: "u25l1",
          title: "出社と朝のあいさつ",
          exercises: [
            L("早上好,今天来得真早", "zǎoshang hǎo, jīntiān lái de zhēn zǎo", "おはよう、今日は来るのが早いですね", "おはよう、今日は遅いですね", "こんにちは、お久しぶりです"),
            T("别忘了打卡", "bié wàng le dǎkǎ", "打刻を忘れないで", "鍵を忘れないで", "名刺を忘れないで"),
            S("我九点上班,六点下班", "wǒ jiǔ diǎn shàngbān, liù diǎn xiàbān", "9時に出勤して、6時に退勤します"),
            W("出勤する", "shàngbān", "上班"),
            L("中午休息一个小时", "zhōngwǔ xiūxi yí ge xiǎoshí", "お昼は1時間休みます", "お昼は30分休みます", "お昼休みはありません"),
            R("我们公司九点上班,但是很多人八点半就到了。大家先喝杯咖啡,看看邮件,然后开始工作。", "Wǒmen gōngsī jiǔ diǎn shàngbān, dànshì hěn duō rén bā diǎn bàn jiù dào le. Dàjiā xiān hē bēi kāfēi, kànkan yóujiàn, ránhòu kāishǐ gōngzuò.", "多くの人は何時に会社に着きますか?", "8時半", "9時", "8時"),
            P("办公室", "オフィス", "bàngōngshì"),
          ],
        },
        {
          id: "u25l2",
          title: "仕事を頼む・引き受ける",
          exercises: [
            L("能帮我复印一下这份文件吗", "néng bāng wǒ fùyìn yíxià zhè fèn wénjiàn ma", "この書類をコピーしてもらえますか?", "この書類をスキャンしてもらえますか?", "この書類を捨ててもらえますか?"),
            T("这件事就交给我吧", "zhè jiàn shì jiù jiāo gěi wǒ ba", "この件は私に任せてください", "この件はもう終わりました", "この件は上司に聞いてください"),
            S("这个什么时候要?", "zhège shénme shíhou yào?", "これはいつまでに必要ですか?"),
            W("コピーする", "fùyìn", "复印"),
            L("我手上的事比较多,明天可以吗", "wǒ shǒu shang de shì bǐjiào duō, míngtiān kěyǐ ma", "今は抱えている仕事が多いので、明日でもいいですか?", "今は暇なので、すぐやります", "明日は休みなので、今日やります"),
            R("部长让我在周三之前整理好上个月的销售数据,做成表格发给他。", "Bùzhǎng ràng wǒ zài zhōusān zhīqián zhěnglǐ hǎo shàng ge yuè de xiāoshòu shùjù, zuòchéng biǎogé fā gěi tā.", "部長に頼まれたことは?", "先月の売上データを表にまとめて送る", "水曜の会議を準備する", "来月の計画を立てる"),
            P("帮忙", "手伝う", "bāngmáng"),
          ],
        },
        {
          id: "u25l3",
          title: "退勤と残業",
          exercises: [
            L("我先走了,明天见", "wǒ xiān zǒu le, míngtiān jiàn", "お先に失礼します、また明日", "先に行ってください", "明日は来ません"),
            T("今天又要加班", "jīntiān yòu yào jiābān", "今日もまた残業です", "今日は残業がありません", "今日は早く帰れます"),
            S("辛苦了,早点回去休息吧", "xīnkǔ le, zǎo diǎn huíqu xiūxi ba", "お疲れさま、早めに帰って休んでね"),
            W("残業する", "jiābān", "加班"),
            L("这个月我已经加了二十个小时的班", "zhège yuè wǒ yǐjīng jiā le èrshí ge xiǎoshí de bān", "今月はもう20時間残業しました", "今月は残業がありませんでした", "今月は20日休みました"),
            R("我们公司规定,晚上八点以后加班要提前申请,周末加班可以调休。", "Wǒmen gōngsī guīdìng, wǎnshang bā diǎn yǐhòu jiābān yào tíqián shēnqǐng, zhōumò jiābān kěyǐ tiáoxiū.", "週末に残業するとどうなりますか?", "振替休日が取れる", "残業代が2倍になる", "申請が不要になる"),
            P("下班", "退勤する", "xiàbān"),
          ],
        },
      ],
    },
    {
      id: "u26",
      title: "展示会と工場見学",
      description: "ブースで説明する・工場を案内する・フォローアップ",
      icon: "🏭",
      lessons: [
        {
          id: "u26l1",
          title: "展示会のブース",
          exercises: [
            L("欢迎参观我们的展位", "huānyíng cānguān wǒmen de zhǎnwèi", "私たちのブースへようこそ", "私たちの工場へようこそ", "私たちの会社へようこそ"),
            T("这是我们今年的新产品", "zhè shì wǒmen jīnnián de xīn chǎnpǐn", "これは今年の新製品です", "これは去年の人気商品です", "これは試作品です"),
            S("可以交换一下名片吗?", "kěyǐ jiāohuàn yíxià míngpiàn ma?", "名刺交換をさせていただけますか?"),
            W("展示会", "zhǎnhuì", "展会"),
            L("样品可以免费寄给您", "yàngpǐn kěyǐ miǎnfèi jì gěi nín", "サンプルは無料でお送りできます", "サンプルは有料です", "サンプルは売り切れました"),
            R("这次展会我们一共收到了八十多张名片,其中有二十家公司对新产品很感兴趣。", "Zhè cì zhǎnhuì wǒmen yígòng shōudào le bāshí duō zhāng míngpiàn, qízhōng yǒu èrshí jiā gōngsī duì xīn chǎnpǐn hěn gǎn xìngqù.", "新製品に興味を示した会社は何社?", "20社", "80社", "8社"),
            P("参观", "見学する", "cānguān"),
          ],
        },
        {
          id: "u26l2",
          title: "工場見学",
          exercises: [
            L("这是我们的生产线", "zhè shì wǒmen de shēngchǎnxiàn", "これが私たちの生産ラインです", "これが私たちの倉庫です", "これが私たちの研究所です"),
            T("我们每个月能生产十万件", "wǒmen měi ge yuè néng shēngchǎn shíwàn jiàn", "毎月10万個生産できます", "毎日10万個生産できます", "毎月1万個生産できます"),
            S("参观的时候请戴好安全帽", "cānguān de shíhou qǐng dài hǎo ānquánmào", "見学のときはヘルメットをかぶってください"),
            W("工場", "gōngchǎng", "工厂"),
            L("这台设备是从日本进口的", "zhè tái shèbèi shì cóng Rìběn jìnkǒu de", "この設備は日本から輸入したものです", "この設備は日本に輸出します", "この設備は自社で作りました"),
            R("工厂有三条生产线,员工大约三百人。为了保证质量,每个产品出厂前都要经过检验。", "Gōngchǎng yǒu sān tiáo shēngchǎnxiàn, yuángōng dàyuē sānbǎi rén. Wèile bǎozhèng zhìliàng, měi ge chǎnpǐn chūchǎng qián dōu yào jīngguò jiǎnyàn.", "品質を保つために何をしていますか?", "出荷前にすべて検査する", "生産ラインを増やす", "従業員を増やす"),
            P("产能", "生産能力", "chǎnnéng"),
          ],
        },
        {
          id: "u26l3",
          title: "見学後のフォローアップ",
          exercises: [
            L("感谢您百忙之中来参观", "gǎnxiè nín bǎimáng zhīzhōng lái cānguān", "お忙しいところご見学いただきありがとうございました", "見学は来週にお願いします", "見学は中止になりました"),
            T("报价单我们明天发给您", "bàojiàdān wǒmen míngtiān fā gěi nín", "見積書は明日お送りします", "見積書はもうお送りしました", "見積書は必要ありません"),
            S("如果有任何问题,请随时联系我", "rúguǒ yǒu rènhé wèntí, qǐng suíshí liánxì wǒ", "何かあれば、いつでもご連絡ください"),
            W("連絡を保つ", "bǎochí liánxì", "保持联系"),
            L("我们希望能尽快安排第一批订单", "wǒmen xīwàng néng jǐnkuài ānpái dì yī pī dìngdān", "最初の注文をできるだけ早く手配したいです", "注文はしばらく見送ります", "注文をキャンセルしたいです"),
            R("田中先生:感谢贵公司昨天的热情接待。我们对产品质量很满意,下周会把具体的采购数量告诉您。", "Tiánzhōng xiānsheng: Gǎnxiè guì gōngsī zuótiān de rèqíng jiēdài. Wǒmen duì chǎnpǐn zhìliàng hěn mǎnyì, xià zhōu huì bǎ jùtǐ de cǎigòu shùliàng gàosu nín.", "来週何を知らせると言っていますか?", "具体的な購入数量", "見積もりの金額", "次の見学日"),
            P("订单", "注文", "dìngdān"),
          ],
        },
      ],
    },
    {
      id: "u27",
      title: "営業とマーケティング",
      description: "製品を売り込む・価格交渉・販促と市場",
      icon: "📈",
      lessons: [
        {
          id: "u27l1",
          title: "製品を売り込む",
          exercises: [
            L("我们的产品性价比很高", "wǒmen de chǎnpǐn xìngjiàbǐ hěn gāo", "当社の製品はコスパがとても高いです", "当社の製品は価格が高いです", "当社の製品は品質が低いです"),
            T("这款产品最大的卖点是省电", "zhè kuǎn chǎnpǐn zuì dà de màidiǎn shì shěng diàn", "この製品の最大のセールスポイントは省エネです", "この製品の最大の欠点は電気代です", "この製品は電池が長持ちしません"),
            S("我先给您介绍一下我们的产品", "wǒ xiān gěi nín jièshào yíxià wǒmen de chǎnpǐn", "まず当社の製品をご紹介します"),
            W("顧客", "kèhù", "客户"),
            L("跟竞争对手相比,我们的售后服务更好", "gēn jìngzhēng duìshǒu xiāngbǐ, wǒmen de shòuhòu fúwù gèng hǎo", "競合と比べて、当社のアフターサービスの方が優れています", "競合と比べて、当社の価格の方が高いです", "競合と同じサービスです"),
            R("这款空气净化器很安静,而且滤网一年只需要换一次,很适合放在办公室。", "Zhè kuǎn kōngqì jìnghuàqì hěn ānjìng, érqiě lǜwǎng yì nián zhǐ xūyào huàn yí cì, hěn shìhé fàng zài bàngōngshì.", "フィルターの交換頻度は?", "1年に1回", "1か月に1回", "交換不要"),
            P("产品", "製品", "chǎnpǐn"),
          ],
        },
        {
          id: "u27l2",
          title: "価格交渉",
          exercises: [
            L("价格能再便宜一点吗", "jiàgé néng zài piányi yìdiǎn ma", "もう少し安くなりませんか?", "価格はこれで決まりです", "もっと高くてもいいです"),
            T("如果订一千个以上,可以打九折", "rúguǒ dìng yìqiān ge yǐshàng, kěyǐ dǎ jiǔ zhé", "1000個以上注文なら10%引きにできます", "1000個以上注文なら90%引きにできます", "1000個未満は注文できません"),
            S("这已经是我们的最低价了", "zhè yǐjīng shì wǒmen de zuì dī jià le", "これがすでに当社の最低価格です"),
            W("割引", "zhékòu", "折扣"),
            L("我们需要跟公司商量一下", "wǒmen xūyào gēn gōngsī shāngliang yíxià", "会社と相談する必要があります", "今すぐ決められます", "もう会社の許可を取りました"),
            R("客户希望单价降低百分之十。我们提出:如果付款期限从九十天改为三十天,可以降低百分之五。", "Kèhù xīwàng dānjià jiàngdī bǎi fēn zhī shí. Wǒmen tíchū: rúguǒ fùkuǎn qīxiàn cóng jiǔshí tiān gǎiwéi sānshí tiān, kěyǐ jiàngdī bǎi fēn zhī wǔ.", "5%値下げする条件は?", "支払い期限を30日に短くすること", "注文数を2倍にすること", "契約を3年にすること"),
            P("价格", "価格", "jiàgé"),
          ],
        },
        {
          id: "u27l3",
          title: "販促と市場",
          exercises: [
            L("我们打算在网上做推广", "wǒmen dǎsuàn zài wǎngshang zuò tuīguǎng", "ネットでプロモーションをするつもりです", "テレビ広告を出すつもりです", "宣伝はしない予定です"),
            T("直播带货的效果非常好", "zhíbō dàihuò de xiàoguǒ fēicháng hǎo", "ライブコマースの効果がとても高い", "ライブコマースはもう古い", "ライブ配信は禁止されている"),
            S("我们的市场份额去年增长了三个百分点", "wǒmen de shìchǎng fèn'é qùnián zēngzhǎng le sān ge bǎifēndiǎn", "当社の市場シェアは昨年3ポイント伸びました"),
            W("市場", "shìchǎng", "市场"),
            L("目标客户是二三十岁的年轻人", "mùbiāo kèhù shì èr-sānshí suì de niánqīngrén", "ターゲット顧客は20〜30代の若者です", "ターゲット顧客は高齢者です", "ターゲット顧客は企業です"),
            R("去年双十一,我们在网上的销售额比前年增长了一倍,主要是因为请了几位网红做直播。", "Qùnián Shuāng Shíyī, wǒmen zài wǎngshang de xiāoshòu'é bǐ qiánnián zēngzhǎng le yí bèi, zhǔyào shì yīnwèi qǐng le jǐ wèi wǎnghóng zuò zhíbō.", "売上が伸びた主な理由は?", "インフルエンサーにライブ配信を頼んだ", "値下げをした", "店舗を増やした"),
            P("推广", "プロモーション", "tuīguǎng"),
          ],
        },
      ],
    },
    {
      id: "u28",
      title: "品質管理と生産",
      description: "不良の報告・原因と対策・生産計画と納期",
      icon: "🔍",
      lessons: [
        {
          id: "u28l1",
          title: "品質の問題",
          exercises: [
            L("这批货的不良率太高了", "zhè pī huò de bùliánglǜ tài gāo le", "このロットの不良率が高すぎます", "このロットは全部合格です", "このロットは数量が足りません"),
            T("检验结果全部合格", "jiǎnyàn jiéguǒ quánbù hégé", "検査結果はすべて合格です", "検査結果は一部不合格です", "検査はまだ終わっていません"),
            S("请把不良品的照片发给我们", "qǐng bǎ bùliángpǐn de zhàopiàn fā gěi wǒmen", "不良品の写真を送ってください"),
            W("品質", "zhìliàng", "质量"),
            L("我们发现有一部分产品尺寸不对", "wǒmen fāxiàn yǒu yí bùfen chǎnpǐn chǐcùn bú duì", "一部の製品のサイズが違っていました", "一部の製品の色が違っていました", "製品はすべて正常です"),
            R("客户反映,五千个零件中有一百个有划痕。我们马上安排了全数检查。", "Kèhù fǎnyìng, wǔqiān ge língjiàn zhōng yǒu yìbǎi ge yǒu huáhén. Wǒmen mǎshàng ānpái le quánshù jiǎnchá.", "傷があった部品はいくつ?", "100個", "5000個", "50個"),
            P("合格", "合格", "hégé"),
          ],
        },
        {
          id: "u28l2",
          title: "原因と対策",
          exercises: [
            L("我们正在分析原因", "wǒmen zhèngzài fēnxī yuányīn", "現在原因を分析しています", "原因はもう分かりました", "原因は分かりません"),
            T("请在一周内提交改善报告", "qǐng zài yì zhōu nèi tíjiāo gǎishàn bàogào", "1週間以内に改善報告書を提出してください", "1か月以内に返品してください", "1週間後に会議をしましょう"),
            S("我们会采取措施,防止再次发生", "wǒmen huì cǎiqǔ cuòshī, fángzhǐ zàicì fāshēng", "再発防止のための措置を取ります"),
            W("原因", "yuányīn", "原因"),
            L("问题出在包装环节", "wèntí chū zài bāozhuāng huánjié", "問題は梱包工程で起きていました", "問題は設計にありました", "問題は輸送中に起きました"),
            R("经过调查,不良的原因是机器的温度设定有误。我们已经修改了设定,并增加了每天的点检。", "Jīngguò diàochá, bùliáng de yuányīn shì jīqì de wēndù shèdìng yǒu wù. Wǒmen yǐjīng xiūgǎi le shèdìng, bìng zēngjiā le měitiān de diǎnjiǎn.", "不良の原因は?", "機械の温度設定の誤り", "材料の不良", "作業員のミス"),
            P("措施", "措置・対策", "cuòshī"),
          ],
        },
        {
          id: "u28l3",
          title: "生産計画と納期",
          exercises: [
            L("下个月的生产计划已经排满了", "xià ge yuè de shēngchǎn jìhuà yǐjīng pái mǎn le", "来月の生産計画はもういっぱいです", "来月はまだ余裕があります", "来月は生産を止めます"),
            T("这个订单能不能加急?", "zhège dìngdān néng bu néng jiājí?", "この注文を急ぎで対応できますか?", "この注文をキャンセルできますか?", "この注文を分割できますか?"),
            S("交期最快也要三个星期", "jiāoqī zuì kuài yě yào sān ge xīngqī", "納期は最短でも3週間かかります"),
            W("納期", "jiāoqī", "交期"),
            L("原材料涨价了,成本增加了不少", "yuáncáiliào zhǎngjià le, chéngběn zēngjiā le bù shǎo", "原材料が値上がりして、コストがかなり増えました", "原材料が値下がりしました", "コストは変わりません"),
            R("因为零件供应不足,原定十五号的交货要推迟到二十五号。我们对此深表歉意。", "Yīnwèi língjiàn gōngyìng bùzú, yuándìng shíwǔ hào de jiāohuò yào tuīchí dào èrshíwǔ hào. Wǒmen duì cǐ shēn biǎo qiànyì.", "新しい納品日は?", "25日", "15日", "5日"),
            P("成本", "コスト", "chéngběn"),
          ],
        },
      ],
    },
    {
      id: "u29",
      title: "マネジメントと評価",
      description: "目標設定・フィードバック・チームをまとめる",
      icon: "👔",
      lessons: [
        {
          id: "u29l1",
          title: "目標を立てる",
          exercises: [
            L("这个季度的目标是销售额增长百分之二十", "zhège jìdù de mùbiāo shì xiāoshòu'é zēngzhǎng bǎi fēn zhī èrshí", "今四半期の目標は売上20%増です", "今年の目標は売上20%増です", "今四半期の売上は20%減りました"),
            T("目标一定要具体、可以衡量", "mùbiāo yídìng yào jùtǐ, kěyǐ héngliáng", "目標は必ず具体的で測定可能に", "目標は大きいほどよい", "目標は毎月変えるべき"),
            S("我们先把大目标分解成小目标", "wǒmen xiān bǎ dà mùbiāo fēnjiě chéng xiǎo mùbiāo", "まず大きな目標を小さな目標に分けましょう"),
            W("目標", "mùbiāo", "目标"),
            L("每个人的考核指标都不一样", "měi ge rén de kǎohé zhǐbiāo dōu bù yíyàng", "評価指標は人によって違います", "評価指標は全員同じです", "評価はありません"),
            R("今年部门的重点有两个:一是开发三家新客户,二是把客户投诉减少一半。", "Jīnnián bùmén de zhòngdiǎn yǒu liǎng ge: yī shì kāifā sān jiā xīn kèhù, èr shì bǎ kèhù tóusù jiǎnshǎo yíbàn.", "今年の重点に含まれないものは?", "コストを半分にする", "新規顧客を3社開拓する", "クレームを半分に減らす"),
            P("季度", "四半期", "jìdù"),
          ],
        },
        {
          id: "u29l2",
          title: "フィードバック",
          exercises: [
            L("这次的方案你做得很好", "zhè cì de fāng'àn nǐ zuò de hěn hǎo", "今回の企画はよくできていました", "今回の企画はやり直しです", "今回の企画はまだですか"),
            T("还有几个地方需要改进", "hái yǒu jǐ ge dìfang xūyào gǎijìn", "まだいくつか改善が必要な点があります", "改善点はありません", "すべてやり直してください"),
            S("我给你提几点建议", "wǒ gěi nǐ tí jǐ diǎn jiànyì", "いくつかアドバイスをさせてください"),
            W("改善する", "gǎijìn", "改进"),
            L("你有什么想法可以直接跟我说", "nǐ yǒu shénme xiǎngfǎ kěyǐ zhíjiē gēn wǒ shuō", "何か考えがあれば直接言ってください", "意見はメールで出してください", "意見は必要ありません"),
            R("面谈的时候,经理先肯定了小刘的努力,然后指出他报告写得太长,希望以后能先写结论。", "Miàntán de shíhou, jīnglǐ xiān kěndìng le Xiǎo Liú de nǔlì, ránhòu zhǐchū tā bàogào xiě de tài cháng, xīwàng yǐhòu néng xiān xiě jiélùn.", "マネージャーの改善要望は?", "報告書は結論から書く", "もっと長い報告書を書く", "報告を毎日する"),
            P("建议", "提案・アドバイス", "jiànyì"),
          ],
        },
        {
          id: "u29l3",
          title: "チームをまとめる",
          exercises: [
            L("我们来分一下工", "wǒmen lái fēn yíxià gōng", "役割分担をしましょう", "休憩しましょう", "解散しましょう"),
            T("团队合作比个人能力更重要", "tuánduì hézuò bǐ gèrén nénglì gèng zhòngyào", "チームワークは個人の能力より大切です", "個人の能力が一番大切です", "チームは小さいほどよい"),
            S("有问题大家一起想办法", "yǒu wèntí dàjiā yìqǐ xiǎng bànfǎ", "問題があればみんなで解決策を考えましょう"),
            W("責任", "zérèn", "责任"),
            L("这个项目由小王负责对接客户", "zhège xiàngmù yóu Xiǎo Wáng fùzé duìjiē kèhù", "このプロジェクトは王さんが顧客窓口を担当します", "このプロジェクトは王さんが設計を担当します", "このプロジェクトは王さんが外れます"),
            R("新团队刚成立,成员来自三个不同的部门。经理每周五组织一次交流会,让大家分享进展和遇到的困难。", "Xīn tuánduì gāng chénglì, chéngyuán láizì sān ge bùtóng de bùmén. Jīnglǐ měi zhōuwǔ zǔzhī yí cì jiāoliúhuì, ràng dàjiā fēnxiǎng jìnzhǎn hé yùdào de kùnnan.", "毎週金曜日に何をしますか?", "進捗や困りごとを共有する会", "チームの飲み会", "個人面談"),
            P("团队", "チーム", "tuánduì"),
          ],
        },
      ],
    },
    {
      id: "u30",
      title: "貿易実務",
      description: "取引条件・船積みと書類・代金決済",
      icon: "🚢",
      lessons: [
        {
          id: "u30l1",
          title: "取引条件",
          exercises: [
            L("付款方式是信用证", "fùkuǎn fāngshì shì xìnyòngzhèng", "支払い方法は信用状(L/C)です", "支払い方法は現金です", "支払い方法は分割です"),
            T("价格按离岸价计算", "jiàgé àn lí'ànjià jìsuàn", "価格はFOB価格で計算します", "価格は着払いで計算します", "価格は税込みで計算します"),
            S("运费和保险费由卖方负担", "yùnfèi hé bǎoxiǎnfèi yóu màifāng fùdān", "運賃と保険料は売り手が負担します"),
            W("支払い方法", "fùkuǎn fāngshì", "付款方式"),
            L("最小起订量是五百个", "zuì xiǎo qǐdìngliàng shì wǔbǎi ge", "最小注文数量は500個です", "最大注文数量は500個です", "在庫は500個です"),
            R("双方约定:百分之三十的货款在签合同后预付,剩下的百分之七十在见到提单复印件后支付。", "Shuāngfāng yuēdìng: bǎi fēn zhī sānshí de huòkuǎn zài qiān hétong hòu yùfù, shèngxia de bǎi fēn zhī qīshí zài jiàndào tídān fùyìnjiàn hòu zhīfù.", "残りの70%はいつ支払いますか?", "B/Lのコピーを確認した後", "契約書に署名した後", "貨物が届いて1か月後"),
            P("信用证", "信用状(L/C)", "xìnyòngzhèng"),
          ],
        },
        {
          id: "u30l2",
          title: "船積みと書類",
          exercises: [
            L("我们已经订好舱位了", "wǒmen yǐjīng dìng hǎo cāngwèi le", "船のスペースはもう予約しました", "船はもう出港しました", "船の予約がまだです"),
            T("货物预计下周五装船", "huòwù yùjì xià zhōuwǔ zhuāngchuán", "貨物は来週金曜に船積み予定です", "貨物は来週金曜に到着予定です", "貨物は来週金曜に検査予定です"),
            S("请尽快寄出正本提单", "qǐng jǐnkuài jìchū zhèngběn tídān", "B/Lの原本をできるだけ早く送ってください"),
            W("船荷証券(B/L)", "tídān", "提单"),
            L("商业发票上的金额和合同不一致", "shāngyè fāpiào shang de jīn'é hé hétong bù yízhì", "コマーシャルインボイスの金額が契約書と一致しません", "インボイスの金額は正しいです", "インボイスがまだ届いていません"),
            R("出口需要准备的单据有:商业发票、装箱单、提单和原产地证明。有的国家还要求提供检验证书。", "Chūkǒu xūyào zhǔnbèi de dānjù yǒu: shāngyè fāpiào, zhuāngxiāngdān, tídān hé yuánchǎndì zhèngmíng. Yǒude guójiā hái yāoqiú tígōng jiǎnyàn zhèngshū.", "一部の国で追加で求められる書類は?", "検査証明書", "パッキングリスト", "原産地証明"),
            P("装船", "船積みする", "zhuāngchuán"),
          ],
        },
        {
          id: "u30l3",
          title: "代金決済",
          exercises: [
            L("预付款已经汇过去了", "yùfùkuǎn yǐjīng huì guòqu le", "前払い金はもう送金しました", "前払い金はまだ送金していません", "前払い金は不要です"),
            T("尾款请在收货后三十天内支付", "wěikuǎn qǐng zài shōuhuò hòu sānshí tiān nèi zhīfù", "残金は受領後30日以内にお支払いください", "残金は出荷前にお支払いください", "残金はありません"),
            S("请提供一下贵公司的银行账户信息", "qǐng tígōng yíxià guì gōngsī de yínháng zhànghù xìnxī", "御社の銀行口座情報をご提供ください"),
            W("送金する", "huìkuǎn", "汇款"),
            L("因为汇率变动,我们的利润减少了", "yīnwèi huìlǜ biàndòng, wǒmen de lìrùn jiǎnshǎo le", "為替の変動で利益が減りました", "為替の変動で利益が増えました", "為替の影響はありませんでした"),
            R("我们收到的款项比发票金额少了三百美元,原因是中间银行扣了手续费。", "Wǒmen shōudào de kuǎnxiàng bǐ fāpiào jīn'é shǎo le sānbǎi měiyuán, yuányīn shì zhōngjiān yínháng kòu le shǒuxùfèi.", "入金額が少なかった理由は?", "中継銀行が手数料を差し引いた", "相手が値引きを求めた", "為替レートが変わった"),
            P("汇率", "為替レート", "huìlǜ"),
          ],
        },
      ],
    },
    {
      id: "u31",
      title: "経済ニュースを読む",
      description: "景気と市場・企業決算・政策と規制",
      icon: "📰",
      lessons: [
        {
          id: "u31l1",
          title: "景気と市場",
          exercises: [
            L("今年第一季度经济增长百分之五", "jīnnián dì yī jìdù jīngjì zēngzhǎng bǎi fēn zhī wǔ", "今年第1四半期の経済成長率は5%", "今年の失業率は5%", "今年第1四半期の輸出は5%減"),
            T("消费市场逐渐回暖", "xiāofèi shìchǎng zhújiàn huínuǎn", "消費市場は徐々に回復している", "消費市場は急速に冷え込んでいる", "消費市場は変化がない"),
            S("出口同比增长了百分之八", "chūkǒu tóngbǐ zēngzhǎng le bǎi fēn zhī bā", "輸出は前年同期比で8%増加しました"),
            W("経済", "jīngjì", "经济"),
            L("房地产市场仍然低迷", "fángdìchǎn shìchǎng réngrán dīmí", "不動産市場は依然として低迷しています", "不動産市場は好調です", "不動産価格が急上昇しました"),
            R("数据显示,上个月社会消费品零售总额同比增长百分之四,其中网上零售增长较快。", "Shùjù xiǎnshì, shàng ge yuè shèhuì xiāofèipǐn língshòu zǒng'é tóngbǐ zēngzhǎng bǎi fēn zhī sì, qízhōng wǎngshang língshòu zēngzhǎng jiào kuài.", "特に伸びが速かったのは?", "ネット小売", "自動車販売", "不動産"),
            P("同比", "前年同期比", "tóngbǐ"),
          ],
        },
        {
          id: "u31l2",
          title: "企業ニュース",
          exercises: [
            L("这家公司昨天发布了财报", "zhè jiā gōngsī zuótiān fābù le cáibào", "この会社は昨日決算を発表しました", "この会社は昨日上場しました", "この会社は昨日倒産しました"),
            T("营业收入创历史新高", "yíngyè shōurù chuàng lìshǐ xīngāo", "売上高が過去最高を記録した", "売上高が過去最低になった", "売上高は前年並みだった"),
            S("净利润同比下降了百分之十二", "jìnglìrùn tóngbǐ xiàjiàng le bǎi fēn zhī shí'èr", "純利益は前年同期比12%減少しました"),
            W("利益", "lìrùn", "利润"),
            L("两家公司宣布合并", "liǎng jiā gōngsī xuānbù hébìng", "2社が合併を発表しました", "2社が提携を解消しました", "2社が訴訟を起こしました"),
            R("该公司表示,由于海外业务扩张,明年计划新招聘两千名员工,并在东南亚建设新工厂。", "Gāi gōngsī biǎoshì, yóuyú hǎiwài yèwù kuòzhāng, míngnián jìhuà xīn zhāopìn liǎngqiān míng yuángōng, bìng zài Dōngnányà jiànshè xīn gōngchǎng.", "新工場はどこに建設しますか?", "東南アジア", "日本", "ヨーロッパ"),
            P("财报", "決算報告", "cáibào"),
          ],
        },
        {
          id: "u31l3",
          title: "政策と規制",
          exercises: [
            L("政府出台了新的扶持政策", "zhèngfǔ chūtái le xīn de fúchí zhèngcè", "政府が新たな支援政策を打ち出しました", "政府が規制を強化しました", "政府が政策を撤回しました"),
            T("监管部门加强了对数据安全的检查", "jiānguǎn bùmén jiāqiáng le duì shùjù ānquán de jiǎnchá", "規制当局がデータセキュリティの検査を強化した", "規制当局がデータ規制を緩めた", "規制当局が検査を中止した"),
            S("新规定从下个月一号开始实施", "xīn guīdìng cóng xià ge yuè yī hào kāishǐ shíshī", "新しい規定は来月1日から施行されます"),
            W("政策", "zhèngcè", "政策"),
            L("对日本游客实行免签政策", "duì Rìběn yóukè shíxíng miǎnqiān zhèngcè", "日本人観光客にビザ免除政策を実施する", "日本人観光客のビザ申請を厳しくする", "日本人観光客の入国を制限する"),
            R("为了吸引外资,当地政府对新设立的外资企业提供三年的税收优惠。", "Wèile xīyǐn wàizī, dāngdì zhèngfǔ duì xīn shèlì de wàizī qǐyè tígōng sān nián de shuìshōu yōuhuì.", "外資企業への優遇措置は?", "3年間の税制優遇", "土地の無償提供", "ビザの免除"),
            P("实施", "実施する・施行する", "shíshī"),
          ],
        },
      ],
    },
    {
      id: "u32",
      title: "スピーチと交渉の仕上げ",
      description: "あいさつスピーチ・難しい交渉・宴席の締めくくり",
      icon: "🎤",
      lessons: [
        {
          id: "u32l1",
          title: "あいさつスピーチ",
          exercises: [
            L("尊敬的各位来宾,大家晚上好", "zūnjìng de gèwèi láibīn, dàjiā wǎnshang hǎo", "ご来賓の皆さま、こんばんは", "社員の皆さん、おはようございます", "お客様、いらっしゃいませ"),
            T("首先,我代表公司向各位表示感谢", "shǒuxiān, wǒ dàibiǎo gōngsī xiàng gèwèi biǎoshì gǎnxiè", "まず、会社を代表して皆さまに感謝申し上げます", "まず、自己紹介をさせていただきます", "まず、お詫び申し上げます"),
            S("感谢大家多年来的支持与合作", "gǎnxiè dàjiā duō nián lái de zhīchí yǔ hézuò", "長年のご支援とご協力に感謝いたします"),
            W("代表する", "dàibiǎo", "代表"),
            L("希望我们今后继续加强合作", "xīwàng wǒmen jīnhòu jìxù jiāqiáng hézuò", "今後も協力関係を一層強めていきたいです", "今後の協力は見直したいです", "今回で協力は終わりです"),
            R("今年是我们两家公司合作的第十年。十年来,我们一起克服了很多困难,也取得了很好的成绩。", "Jīnnián shì wǒmen liǎng jiā gōngsī hézuò de dì shí nián. Shí nián lái, wǒmen yìqǐ kèfú le hěn duō kùnnan, yě qǔdé le hěn hǎo de chéngjì.", "2社の協力は何年目ですか?", "10年目", "1年目", "3年目"),
            P("来宾", "来賓", "láibīn"),
          ],
        },
        {
          id: "u32l2",
          title: "難しい交渉",
          exercises: [
            L("我们各让一步怎么样", "wǒmen gè ràng yí bù zěnmeyàng", "お互いに一歩ずつ譲りませんか?", "こちらは一歩も譲れません", "今日は交渉をやめましょう"),
            T("这是我们的底线", "zhè shì wǒmen de dǐxiàn", "これが私たちの譲れない一線です", "これが私たちの最初の提案です", "これは参考価格です"),
            S("我们希望找到一个双赢的方案", "wǒmen xīwàng zhǎodào yí ge shuāngyíng de fāng'àn", "双方にとってプラスになる案を見つけたいです"),
            W("ウィンウィン", "shuāngyíng", "双赢"),
            L("这个条件我们恐怕很难接受", "zhège tiáojiàn wǒmen kǒngpà hěn nán jiēshòu", "この条件は受け入れるのが難しいと思います", "この条件ですぐ合意します", "この条件で問題ありません"),
            R("对方要求独家代理权,我们提出先签一年的试行合同,如果销售额达到目标,再考虑独家代理。", "Duìfāng yāoqiú dújiā dàilǐquán, wǒmen tíchū xiān qiān yì nián de shìxíng hétong, rúguǒ xiāoshòu'é dádào mùbiāo, zài kǎolǜ dújiā dàilǐ.", "こちらの提案は?", "まず1年の試行契約を結ぶ", "すぐに独占代理権を与える", "交渉を打ち切る"),
            P("底线", "最低ライン", "dǐxiàn"),
          ],
        },
        {
          id: "u32l3",
          title: "宴席の締めくくり",
          exercises: [
            L("为我们的合作干杯", "wèi wǒmen de hézuò gānbēi", "私たちの協力に乾杯", "私たちの成功を祈って", "今日はありがとう"),
            T("我不太会喝酒,我以茶代酒", "wǒ bú tài huì hē jiǔ, wǒ yǐ chá dài jiǔ", "お酒はあまり飲めないので、お茶で代わりに", "お酒が大好きです", "お茶はいりません"),
            S("祝大家身体健康,工作顺利", "zhù dàjiā shēntǐ jiànkāng, gōngzuò shùnlì", "皆さまのご健康とお仕事のご成功をお祈りします"),
            W("乾杯", "gānbēi", "干杯"),
            L("今天招待不周,请多包涵", "jīntiān zhāodài bù zhōu, qǐng duō bāohan", "今日は行き届かない点があり失礼しました", "今日は最高のおもてなしでした", "今日はここまでにしましょう"),
            R("晚宴快结束的时候,王总站起来说:感谢日本朋友远道而来,希望明年我们去日本的时候还能一起喝一杯。", "Wǎnyàn kuài jiéshù de shíhou, Wáng zǒng zhàn qǐlái shuō: Gǎnxiè Rìběn péngyou yuǎndào ér lái, xīwàng míngnián wǒmen qù Rìběn de shíhou hái néng yìqǐ hē yì bēi.", "王社長は来年どうしたいと言っていますか?", "日本に行ったときにまた一緒に飲みたい", "中国でまた宴会を開きたい", "取引をやめたい"),
            P("顺利", "順調である", "shùnlì"),
          ],
        },
      ],
    },
  ];

  UNITS2.forEach((unit) => {
    if (!UNITS.some((u) => u.id === unit.id)) UNITS.push(unit);
  });
})();
