// 中国語学習アプリ - コンテンツデータ
// 各ユニットは複数のレッスンを持ち、各レッスンは4技能(聞く・話す・読む・書く)の
// エクササイズを組み合わせて構成される。

const UNITS = [
  {
    id: "u1",
    title: "あいさつと自己紹介",
    description: "基本のあいさつ表現を身につけよう",
    icon: "👋",
    lessons: [
      {
        id: "u1l1",
        title: "基本のあいさつ",
        exercises: [
          {
            type: "listening_choice",
            audioText: "你好",
            pinyin: "nǐ hǎo",
            prompt: "今聞こえた言葉の意味はどれ?",
            choices: [
              { text: "こんにちは", correct: true },
              { text: "さようなら", correct: false },
              { text: "ありがとう", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "谢谢",
            pinyin: "xièxie",
            prompt: "この言葉の意味は?",
            choices: [
              { text: "ありがとう", correct: true },
              { text: "すみません", correct: false },
              { text: "こんにちは", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "你好",
            pinyin: "nǐ hǎo",
            meaning: "こんにちは",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "listening_choice",
            audioText: "再见",
            pinyin: "zàijiàn",
            prompt: "今聞こえた言葉の意味はどれ?",
            choices: [
              { text: "さようなら", correct: true },
              { text: "おやすみなさい", correct: false },
              { text: "ありがとう", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "こんにちは",
            pinyinHint: "nǐ hǎo",
            answer: "你好",
          },
          {
            type: "reading",
            passage: "你好!谢谢你。再见!",
            passagePinyin: "Nǐ hǎo! Xièxie nǐ. Zàijiàn!",
            question: "この文章に含まれていない表現はどれ?",
            choices: [
              { text: "对不起 (すみません)", correct: true },
              { text: "你好 (こんにちは)", correct: false },
              { text: "谢谢 (ありがとう)", correct: false },
            ],
          },
        ],
      },
      {
        id: "u1l2",
        title: "自己紹介をする",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我叫田中",
            pinyin: "wǒ jiào Tiánzhōng",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "私は田中といいます", correct: true },
              { text: "私は日本人です", correct: false },
              { text: "あなたの名前は何ですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我叫田中",
            pinyin: "wǒ jiào Tiánzhōng",
            meaning: "私は田中といいます",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "translate_choice",
            hanzi: "我是日本人",
            pinyin: "wǒ shì Rìběnrén",
            prompt: "この文の意味は?",
            choices: [
              { text: "私は日本人です", correct: true },
              { text: "私は中国人です", correct: false },
              { text: "あなたは日本人ですか", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "很高兴认识你",
            meaningHint: "お会いできて嬉しいです",
            answer: "hen gaoxing renshi ni",
            answerToned: "hěn gāoxìng rènshi nǐ",
          },
          {
            type: "reading",
            passage: "我叫田中。我是日本人。很高兴认识你。",
            passagePinyin: "Wǒ jiào Tiánzhōng. Wǒ shì Rìběnrén. Hěn gāoxìng rènshi nǐ.",
            question: "この人はどこの国の人ですか?",
            choices: [
              { text: "日本人", correct: true },
              { text: "中国人", correct: false },
              { text: "アメリカ人", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "私は日本人です",
            pinyinHint: "wǒ shì Rìběnrén",
            answer: "我是日本人",
          },
        ],
      },
      {
        id: "u1l3",
        title: "相手に質問する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "你叫什么名字",
            pinyin: "nǐ jiào shénme míngzi",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "あなたの名前は何ですか", correct: true },
              { text: "あなたは元気ですか", correct: false },
              { text: "あなたはどこの国の人ですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "你好吗",
            pinyin: "nǐ hǎo ma",
            meaning: "お元気ですか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "translate_choice",
            hanzi: "你是哪国人",
            pinyin: "nǐ shì nǎ guó rén",
            prompt: "この文の意味は?",
            choices: [
              { text: "あなたはどこの国の人ですか", correct: true },
              { text: "あなたの名前は何ですか", correct: false },
              { text: "あなたは何歳ですか", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "お元気ですか",
            pinyinHint: "nǐ hǎo ma",
            answer: "你好吗",
          },
          {
            type: "reading",
            passage: "A: 你好吗? B: 我很好,谢谢。你呢? A: 我也很好。",
            passagePinyin: "A: Nǐ hǎo ma? B: Wǒ hěn hǎo, xièxie. Nǐ ne? A: Wǒ yě hěn hǎo.",
            question: "Bさんの調子はどうですか?",
            choices: [
              { text: "良い", correct: true },
              { text: "悪い", correct: false },
              { text: "分からない", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "我很好",
            pinyin: "wǒ hěn hǎo",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "私は元気です", correct: true },
              { text: "私は疲れています", correct: false },
              { text: "私は日本人です", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u2",
    title: "数字と時間",
    description: "数字・年齢・時間の表現を学ぼう",
    icon: "🔢",
    lessons: [
      {
        id: "u2l1",
        title: "数字 1〜10",
        exercises: [
          {
            type: "listening_choice",
            audioText: "三",
            pinyin: "sān",
            prompt: "今聞こえた数字はどれ?",
            choices: [
              { text: "3", correct: true },
              { text: "2", correct: false },
              { text: "8", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "七",
            pinyin: "qī",
            prompt: "この漢字が表す数字は?",
            choices: [
              { text: "7", correct: true },
              { text: "9", correct: false },
              { text: "1", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "一,二,三,四,五",
            pinyin: "yī, èr, sān, sì, wǔ",
            meaning: "1、2、3、4、5",
            prompt: "声に出して数字を読んでみましょう",
          },
          {
            type: "writing_cn",
            meaning: "10 (じゅう)",
            pinyinHint: "shí",
            answer: "十",
          },
          {
            type: "listening_choice",
            audioText: "九",
            pinyin: "jiǔ",
            prompt: "今聞こえた数字はどれ?",
            choices: [
              { text: "9", correct: true },
              { text: "6", correct: false },
              { text: "5", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "六",
            meaningHint: "数字の6",
            answer: "liu",
            answerToned: "liù",
          },
        ],
      },
      {
        id: "u2l2",
        title: "年齢を聞く",
        exercises: [
          {
            type: "listening_choice",
            audioText: "你多大了",
            pinyin: "nǐ duō dà le",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "あなたは何歳ですか", correct: true },
              { text: "今何時ですか", correct: false },
              { text: "あなたの名前は?", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我二十岁",
            pinyin: "wǒ èrshí suì",
            meaning: "私は20歳です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "translate_choice",
            hanzi: "我三十岁了",
            pinyin: "wǒ sānshí suì le",
            prompt: "この文の意味は?",
            choices: [
              { text: "私は30歳になりました", correct: true },
              { text: "私は13歳です", correct: false },
              { text: "私は300円持っています", correct: false },
            ],
          },
          {
            type: "reading",
            passage: "A: 你多大了? B: 我二十五岁了。你呢? A: 我二十八岁。",
            passagePinyin: "A: Nǐ duō dà le? B: Wǒ èrshíwǔ suì le. Nǐ ne? A: Wǒ èrshíbā suì.",
            question: "Bさんは何歳ですか?",
            choices: [
              { text: "25歳", correct: true },
              { text: "28歳", correct: false },
              { text: "20歳", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "私は20歳です",
            pinyinHint: "wǒ èrshí suì",
            answer: "我二十岁",
          },
          {
            type: "listening_choice",
            audioText: "二十八",
            pinyin: "èrshíbā",
            prompt: "今聞こえた数字はどれ?",
            choices: [
              { text: "28", correct: true },
              { text: "82", correct: false },
              { text: "18", correct: false },
            ],
          },
        ],
      },
      {
        id: "u2l3",
        title: "時間と曜日",
        exercises: [
          {
            type: "listening_choice",
            audioText: "现在几点",
            pinyin: "xiànzài jǐ diǎn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "今何時ですか", correct: true },
              { text: "今日は何曜日ですか", correct: false },
              { text: "何時に会いますか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "星期一",
            pinyin: "xīngqīyī",
            prompt: "この言葉の意味は?",
            choices: [
              { text: "月曜日", correct: true },
              { text: "日曜日", correct: false },
              { text: "1月", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "现在三点",
            pinyin: "xiànzài sān diǎn",
            meaning: "今3時です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "日曜日",
            pinyinHint: "xīngqītiān",
            answer: "星期天",
          },
          {
            type: "reading",
            passage: "今天是星期一。现在是早上八点。",
            passagePinyin: "Jīntiān shì xīngqīyī. Xiànzài shì zǎoshang bā diǎn.",
            question: "今日は何曜日ですか?",
            choices: [
              { text: "月曜日", correct: true },
              { text: "日曜日", correct: false },
              { text: "土曜日", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "星期五",
            meaningHint: "金曜日",
            answer: "xingqiwu",
            answerToned: "xīngqīwǔ",
          },
        ],
      },
    ],
  },
  {
    id: "u3",
    title: "家族と友達",
    description: "家族の呼び方や紹介の仕方を学ぼう",
    icon: "👨‍👩‍👧‍👦",
    lessons: [
      {
        id: "u3l1",
        title: "家族の呼び方",
        exercises: [
          {
            type: "listening_choice",
            audioText: "爸爸",
            pinyin: "bàba",
            prompt: "今聞こえた言葉の意味はどれ?",
            choices: [
              { text: "お父さん", correct: true },
              { text: "お母さん", correct: false },
              { text: "お兄さん", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "妈妈",
            pinyin: "māma",
            prompt: "この言葉の意味は?",
            choices: [
              { text: "お母さん", correct: true },
              { text: "妹", correct: false },
              { text: "お父さん", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "哥哥,姐姐,弟弟,妹妹",
            pinyin: "gēge, jiějie, dìdi, mèimei",
            meaning: "兄、姉、弟、妹",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "お父さん",
            pinyinHint: "bàba",
            answer: "爸爸",
          },
          {
            type: "listening_choice",
            audioText: "姐姐",
            pinyin: "jiějie",
            prompt: "今聞こえた言葉の意味はどれ?",
            choices: [
              { text: "お姉さん", correct: true },
              { text: "妹", correct: false },
              { text: "お母さん", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "弟弟",
            meaningHint: "弟",
            answer: "didi",
            answerToned: "dìdi",
          },
        ],
      },
      {
        id: "u3l2",
        title: "家族について話す",
        exercises: [
          {
            type: "listening_choice",
            audioText: "你家有几口人",
            pinyin: "nǐ jiā yǒu jǐ kǒu rén",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "あなたの家族は何人ですか", correct: true },
              { text: "あなたは何人兄弟ですか", correct: false },
              { text: "あなたの家はどこですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我家有四口人",
            pinyin: "wǒ jiā yǒu sì kǒu rén",
            meaning: "私の家族は4人です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "translate_choice",
            hanzi: "这是我的爸爸",
            pinyin: "zhè shì wǒ de bàba",
            prompt: "この文の意味は?",
            choices: [
              { text: "これは私の父です", correct: true },
              { text: "これは私の家です", correct: false },
              { text: "これは私の友達です", correct: false },
            ],
          },
          {
            type: "reading",
            passage: "我家有四口人:爸爸、妈妈、姐姐和我。我很喜欢我的家人。",
            passagePinyin: "Wǒ jiā yǒu sì kǒu rén: bàba, māma, jiějie hé wǒ. Wǒ hěn xǐhuan wǒ de jiārén.",
            question: "この人の家族は何人ですか?",
            choices: [
              { text: "4人", correct: true },
              { text: "3人", correct: false },
              { text: "5人", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "私の家族は4人です",
            pinyinHint: "wǒ jiā yǒu sì kǒu rén",
            answer: "我家有四口人",
          },
          {
            type: "listening_choice",
            audioText: "这是我的妈妈",
            pinyin: "zhè shì wǒ de māma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "これは私の母です", correct: true },
              { text: "これは私の姉です", correct: false },
              { text: "これは私の先生です", correct: false },
            ],
          },
        ],
      },
      {
        id: "u3l3",
        title: "友達を紹介する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "这是我的朋友",
            pinyin: "zhè shì wǒ de péngyou",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "これは私の友達です", correct: true },
              { text: "これは私の先生です", correct: false },
              { text: "これは私の家族です", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "他是我的同学",
            pinyin: "tā shì wǒ de tóngxué",
            prompt: "この文の意味は?",
            choices: [
              { text: "彼は私のクラスメートです", correct: true },
              { text: "彼は私の先生です", correct: false },
              { text: "彼女は私の姉です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "她是我的朋友,她很漂亮",
            pinyin: "tā shì wǒ de péngyou, tā hěn piàoliang",
            meaning: "彼女は私の友達で、とても綺麗です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "これは私の友達です",
            pinyinHint: "zhè shì wǒ de péngyou",
            answer: "这是我的朋友",
          },
          {
            type: "reading",
            passage: "这是我的朋友,他叫小明。他是中国人,今年二十岁。",
            passagePinyin: "Zhè shì wǒ de péngyou, tā jiào Xiǎomíng. Tā shì Zhōngguórén, jīnnián èrshí suì.",
            question: "小明さんは何歳ですか?",
            choices: [
              { text: "20歳", correct: true },
              { text: "22歳", correct: false },
              { text: "25歳", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "朋友",
            meaningHint: "友達",
            answer: "pengyou",
            answerToned: "péngyou",
          },
        ],
      },
    ],
  },
  {
    id: "u4",
    title: "日常生活",
    description: "食事・買い物・道案内の表現を学ぼう",
    icon: "🍜",
    lessons: [
      {
        id: "u4l1",
        title: "食事について話す",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我想吃米饭",
            pinyin: "wǒ xiǎng chī mǐfàn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "私はご飯が食べたいです", correct: true },
              { text: "私はお茶が飲みたいです", correct: false },
              { text: "私はお腹がいっぱいです", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "好吃",
            pinyin: "hǎochī",
            prompt: "この言葉の意味は?",
            choices: [
              { text: "美味しい", correct: true },
              { text: "まずい", correct: false },
              { text: "辛い", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "这个很好吃",
            pinyin: "zhège hěn hǎochī",
            meaning: "これはとても美味しいです",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "美味しい",
            pinyinHint: "hǎochī",
            answer: "好吃",
          },
          {
            type: "reading",
            passage: "我喜欢吃中国菜。今天我想吃饺子,因为饺子很好吃。",
            passagePinyin: "Wǒ xǐhuan chī Zhōngguó cài. Jīntiān wǒ xiǎng chī jiǎozi, yīnwèi jiǎozi hěn hǎochī.",
            question: "今日食べたいものは何ですか?",
            choices: [
              { text: "餃子", correct: true },
              { text: "ご飯", correct: false },
              { text: "麺", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "你喜欢吃什么",
            pinyin: "nǐ xǐhuan chī shénme",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "何を食べるのが好きですか", correct: true },
              { text: "何を飲みたいですか", correct: false },
              { text: "お腹が空きましたか", correct: false },
            ],
          },
        ],
      },
      {
        id: "u4l2",
        title: "買い物をする",
        exercises: [
          {
            type: "listening_choice",
            audioText: "这个多少钱",
            pinyin: "zhège duōshao qián",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "これはいくらですか", correct: true },
              { text: "これは何ですか", correct: false },
              { text: "これはどこにありますか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "太贵了",
            pinyin: "tài guì le",
            prompt: "この文の意味は?",
            choices: [
              { text: "高すぎます", correct: true },
              { text: "安すぎます", correct: false },
              { text: "美味しすぎます", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我要这个",
            pinyin: "wǒ yào zhège",
            meaning: "これをください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "いくらですか",
            pinyinHint: "duōshao qián",
            answer: "多少钱",
          },
          {
            type: "reading",
            passage: "A: 这个多少钱? B: 三十块。 A: 太贵了,便宜一点吧。 B: 好的,二十五块。",
            passagePinyin: "A: Zhège duōshao qián? B: Sānshí kuài. A: Tài guì le, piányi yìdiǎn ba. B: Hǎo de, èrshíwǔ kuài.",
            question: "最終的にいくらになりましたか?",
            choices: [
              { text: "25元", correct: true },
              { text: "30元", correct: false },
              { text: "20元", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "便宜",
            meaningHint: "安い",
            answer: "pianyi",
            answerToned: "piányi",
          },
        ],
      },
      {
        id: "u4l3",
        title: "道案内・交通",
        exercises: [
          {
            type: "listening_choice",
            audioText: "地铁站在哪儿",
            pinyin: "dìtiě zhàn zài nǎr",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "地下鉄の駅はどこですか", correct: true },
              { text: "バス停はどこですか", correct: false },
              { text: "トイレはどこですか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "怎么走",
            pinyin: "zěnme zǒu",
            prompt: "この文の意味は?",
            choices: [
              { text: "どうやって行きますか", correct: true },
              { text: "何時に着きますか", correct: false },
              { text: "どこから来ましたか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "一直往前走",
            pinyin: "yìzhí wǎng qián zǒu",
            meaning: "まっすぐ進んでください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "地下鉄の駅",
            pinyinHint: "dìtiě zhàn",
            answer: "地铁站",
          },
          {
            type: "reading",
            passage: "A: 请问,地铁站怎么走? B: 一直往前走,然后往右转就到了。 A: 谢谢你!",
            passagePinyin: "A: Qǐngwèn, dìtiě zhàn zěnme zǒu? B: Yìzhí wǎng qián zǒu, ránhòu wǎng yòu zhuǎn jiù dào le. A: Xièxie nǐ!",
            question: "地下鉄駅へはどう行けばよいですか?",
            choices: [
              { text: "まっすぐ進んでから右に曲がる", correct: true },
              { text: "まっすぐ進んでから左に曲がる", correct: false },
              { text: "後ろに戻る", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "往右转",
            pinyin: "wǎng yòu zhuǎn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "右に曲がる", correct: true },
              { text: "左に曲がる", correct: false },
              { text: "まっすぐ進む", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u5",
    title: "仕事の基本",
    description: "職業・自己紹介・予定調整などビジネスの基本表現",
    icon: "💼",
    lessons: [
      {
        id: "u5l1",
        title: "職業と会社",
        exercises: [
          {
            type: "listening_choice",
            audioText: "你做什么工作",
            pinyin: "nǐ zuò shénme gōngzuò",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "お仕事は何ですか", correct: true },
              { text: "どこの会社ですか", correct: false },
              { text: "何歳ですか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我在贸易公司工作",
            pinyin: "wǒ zài màoyì gōngsī gōngzuò",
            prompt: "この文の意味は?",
            choices: [
              { text: "貿易会社で働いています", correct: true },
              { text: "貿易会社を経営しています", correct: false },
              { text: "貿易の勉強をしています", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "这是我的名片",
            pinyin: "zhè shì wǒ de míngpiàn",
            meaning: "これは私の名刺です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "名刺",
            pinyinHint: "míngpiàn",
            answer: "名片",
          },
          {
            type: "reading",
            passage: "您好,这是我的名片。我在一家贸易公司工作,负责销售。",
            passagePinyin: "Nín hǎo, zhè shì wǒ de míngpiàn. Wǒ zài yì jiā màoyì gōngsī gōngzuò, fùzé xiāoshòu.",
            question: "この人は何を担当していますか?",
            choices: [
              { text: "営業(販売)", correct: true },
              { text: "経理", correct: false },
              { text: "人事", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "请多关照",
            pinyin: "qǐng duō guānzhào",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "どうぞよろしくお願いします", correct: true },
              { text: "ありがとうございます", correct: false },
              { text: "お疲れ様です", correct: false },
            ],
          },
        ],
      },
      {
        id: "u5l2",
        title: "自己紹介(ビジネス)",
        exercises: [
          {
            type: "listening_choice",
            audioText: "很荣幸认识您",
            pinyin: "hěn róngxìng rènshi nín",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "お会いできて光栄です", correct: true },
              { text: "はじめまして", correct: false },
              { text: "お元気ですか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我负责市场部",
            pinyin: "wǒ fùzé shìchǎng bù",
            prompt: "この文の意味は?",
            choices: [
              { text: "マーケティング部を担当しています", correct: true },
              { text: "営業部で働いています", correct: false },
              { text: "人事部の部長です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请多指教",
            pinyin: "qǐng duō zhǐjiào",
            meaning: "ご指導よろしくお願いします",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "荣幸",
            meaningHint: "光栄",
            answer: "rongxing",
            answerToned: "róngxìng",
          },
          {
            type: "reading",
            passage: "我姓王,是这次项目的负责人。请多多关照。",
            passagePinyin: "Wǒ xìng Wáng, shì zhè cì xiàngmù de fùzé rén. Qǐng duōduō guānzhào.",
            question: "この人はプロジェクトの何ですか?",
            choices: [
              { text: "責任者", correct: true },
              { text: "アシスタント", correct: false },
              { text: "新人", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "よろしくお願いします",
            pinyinHint: "qǐng duō guānzhào",
            answer: "请多关照",
          },
        ],
      },
      {
        id: "u5l3",
        title: "時間・予定を調整する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "明天你有空吗",
            pinyin: "míngtiān nǐ yǒu kòng ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "明日お時間ありますか", correct: true },
              { text: "今日は忙しいですか", correct: false },
              { text: "何時に会いますか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我们约在下午三点",
            pinyin: "wǒmen yuē zài xiàwǔ sān diǎn",
            prompt: "この文の意味は?",
            choices: [
              { text: "午後3時に約束しましょう", correct: true },
              { text: "午前3時に会議です", correct: false },
              { text: "3日後に会いましょう", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "几点方便",
            pinyin: "jǐ diǎn fāngbiàn",
            meaning: "何時が都合いいですか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "都合がいい",
            pinyinHint: "fāngbiàn",
            answer: "方便",
          },
          {
            type: "reading",
            passage: "A: 明天下午你有空吗? B: 有,几点方便? A: 三点怎么样? B: 可以,我们三点见。",
            passagePinyin: "A: Míngtiān xiàwǔ nǐ yǒu kòng ma? B: Yǒu, jǐ diǎn fāngbiàn? A: Sān diǎn zěnmeyàng? B: Kěyǐ, wǒmen sān diǎn jiàn.",
            question: "二人は何時に会う約束をしましたか?",
            choices: [
              { text: "3時", correct: true },
              { text: "2時", correct: false },
              { text: "4時", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "我们改天再约",
            pinyin: "wǒmen gǎitiān zài yuē",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "また日を改めて約束しましょう", correct: true },
              { text: "今すぐ会いましょう", correct: false },
              { text: "約束はキャンセルです", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u6",
    title: "電話とメール",
    description: "電話応対・伝言・メールの基本表現",
    icon: "📞",
    lessons: [
      {
        id: "u6l1",
        title: "電話に出る・かける",
        exercises: [
          {
            type: "listening_choice",
            audioText: "喂,请问王经理在吗",
            pinyin: "wéi, qǐngwèn Wáng jīnglǐ zài ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "もしもし、王マネージャーはいらっしゃいますか", correct: true },
              { text: "もしもし、どちら様ですか", correct: false },
              { text: "もしもし、聞こえますか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "请稍等",
            pinyin: "qǐng shāo děng",
            prompt: "この文の意味は?",
            choices: [
              { text: "少々お待ちください", correct: true },
              { text: "もう一度お願いします", correct: false },
              { text: "またかけ直します", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我马上帮您转接",
            pinyin: "wǒ mǎshàng bāng nín zhuǎnjiē",
            meaning: "すぐにおつなぎします",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "少々お待ちください",
            pinyinHint: "qǐng shāo děng",
            answer: "请稍等",
          },
          {
            type: "reading",
            passage: "喂,您好,这里是ABC公司。请问您找哪位?请稍等,我帮您转接。",
            passagePinyin: "Wéi, nín hǎo, zhèlǐ shì ABC gōngsī. Qǐngwèn nín zhǎo nǎ wèi? Qǐng shāo děng, wǒ bāng nín zhuǎnjiē.",
            question: "この会話はどこでの場面ですか?",
            choices: [
              { text: "電話対応", correct: true },
              { text: "レストラン", correct: false },
              { text: "会議", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "电话占线",
            pinyin: "diànhuà zhànxiàn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "電話は話し中です", correct: true },
              { text: "電話番号が違います", correct: false },
              { text: "電話が切れました", correct: false },
            ],
          },
        ],
      },
      {
        id: "u6l2",
        title: "伝言を残す",
        exercises: [
          {
            type: "listening_choice",
            audioText: "他现在不在",
            pinyin: "tā xiànzài bú zài",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "彼は今席を外しています", correct: true },
              { text: "彼はもう帰りました", correct: false },
              { text: "彼は会議中です", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我可以留言吗",
            pinyin: "wǒ kěyǐ liúyán ma",
            prompt: "この文の意味は?",
            choices: [
              { text: "伝言をお願いできますか", correct: true },
              { text: "また電話します", correct: false },
              { text: "メールを送ってもいいですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请他给我回电话",
            pinyin: "qǐng tā gěi wǒ huí diànhuà",
            meaning: "折り返しお電話くださいとお伝えください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "留言",
            meaningHint: "伝言",
            answer: "liuyan",
            answerToned: "liúyán",
          },
          {
            type: "reading",
            passage: "对不起,他现在开会,不在座位上。您要留言吗?好的,请转告他给我回电话。",
            passagePinyin: "Duìbuqǐ, tā xiànzài kāihuì, bú zài zuòwèi shàng. Nín yào liúyán ma? Hǎo de, qǐng zhuǎngào tā gěi wǒ huí diànhuà.",
            question: "相手はなぜ電話に出られませんか?",
            choices: [
              { text: "会議中だから", correct: true },
              { text: "外出しているから", correct: false },
              { text: "体調が悪いから", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "折り返し電話する",
            pinyinHint: "huí diànhuà",
            answer: "回电话",
          },
        ],
      },
      {
        id: "u6l3",
        title: "メールの基本表現",
        exercises: [
          {
            type: "listening_choice",
            audioText: "谢谢您的邮件",
            pinyin: "xièxie nín de yóujiàn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "メールをありがとうございます", correct: true },
              { text: "お電話ありがとうございます", correct: false },
              { text: "ご来社ありがとうございます", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "请查收附件",
            pinyin: "qǐng chá shōu fùjiàn",
            prompt: "この文の意味は?",
            choices: [
              { text: "添付ファイルをご確認ください", correct: true },
              { text: "お電話お待ちしております", correct: false },
              { text: "資料を送ってください", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "期待您的回复",
            pinyin: "qídài nín de huífù",
            meaning: "お返事をお待ちしております",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "添付ファイル",
            pinyinHint: "fùjiàn",
            answer: "附件",
          },
          {
            type: "reading",
            passage: "王经理,您好。附件是本次会议的资料,请查收。如有问题请随时联系我。期待您的回复。",
            passagePinyin: "Wáng jīnglǐ, nín hǎo. Fùjiàn shì běn cì huìyì de zīliào, qǐng chá shōu. Rú yǒu wèntí qǐng suíshí liánxì wǒ. Qídài nín de huífù.",
            question: "このメールに添付されているものは何ですか?",
            choices: [
              { text: "会議資料", correct: true },
              { text: "契約書", correct: false },
              { text: "請求書", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "如有问题请随时联系我",
            pinyin: "rú yǒu wèntí qǐng suíshí liánxì wǒ",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "何か問題があればいつでもご連絡ください", correct: true },
              { text: "問題は今のところありません", correct: false },
              { text: "すぐに返信します", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u7",
    title: "会議と商談",
    description: "会議の進行・意見交換・価格交渉の表現",
    icon: "🤝",
    lessons: [
      {
        id: "u7l1",
        title: "会議を始める",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我们开始吧",
            pinyin: "wǒmen kāishǐ ba",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "それでは始めましょう", correct: true },
              { text: "もう終わりました", correct: false },
              { text: "少し待ちましょう", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "今天的议题是什么",
            pinyin: "jīntiān de yìtí shì shénme",
            prompt: "この文の意味は?",
            choices: [
              { text: "今日の議題は何ですか", correct: true },
              { text: "今日は誰が来ますか", correct: false },
              { text: "会議はいつ終わりますか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请大家看一下资料",
            pinyin: "qǐng dàjiā kàn yíxià zīliào",
            meaning: "皆さん資料をご覧ください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "議題",
            pinyinHint: "yìtí",
            answer: "议题",
          },
          {
            type: "reading",
            passage: "大家好,今天的会议主要讨论新产品的销售计划。我们先看一下资料。",
            passagePinyin: "Dàjiā hǎo, jīntiān de huìyì zhǔyào tǎolùn xīn chǎnpǐn de xiāoshòu jìhuà. Wǒmen xiān kàn yíxià zīliào.",
            question: "今日の会議で主に話し合う内容は?",
            choices: [
              { text: "新商品の販売計画", correct: true },
              { text: "人事異動", correct: false },
              { text: "来期の予算", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "会议到这里结束",
            pinyin: "huìyì dào zhèlǐ jiéshù",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "会議はここまでとします", correct: true },
              { text: "会議はまだ続きます", correct: false },
              { text: "会議は延期します", correct: false },
            ],
          },
        ],
      },
      {
        id: "u7l2",
        title: "意見を言う",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我认为这个方案不错",
            pinyin: "wǒ rènwéi zhège fāng'àn búcuò",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "この案は良いと思います", correct: true },
              { text: "この案には反対です", correct: false },
              { text: "考え直しましょう", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我有不同的看法",
            pinyin: "wǒ yǒu bùtóng de kànfǎ",
            prompt: "この文の意味は?",
            choices: [
              { text: "私は違う意見を持っています", correct: true },
              { text: "私も賛成です", correct: false },
              { text: "よくわかりません", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我同意你的意见",
            pinyin: "wǒ tóngyì nǐ de yìjiàn",
            meaning: "あなたの意見に賛成です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "看法",
            meaningHint: "意見・見方",
            answer: "kanfa",
            answerToned: "kànfǎ",
          },
          {
            type: "reading",
            passage: "A: 我认为应该先降低成本。 B: 我有不同的看法,我觉得应该先提高质量。",
            passagePinyin: "A: Wǒ rènwéi yīnggāi xiān jiàngdī chéngběn. B: Wǒ yǒu bùtóng de kànfǎ, wǒ juéde yīnggāi xiān tígāo zhìliàng.",
            question: "Bさんの考えは?",
            choices: [
              { text: "品質向上を優先すべき", correct: true },
              { text: "コスト削減を優先すべき", correct: false },
              { text: "両方とも不要", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "賛成です",
            pinyinHint: "wǒ tóngyì",
            answer: "我同意",
          },
        ],
      },
      {
        id: "u7l3",
        title: "交渉する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "价格可以再商量吗",
            pinyin: "jiàgé kěyǐ zài shāngliang ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "価格はもう少し相談できますか", correct: true },
              { text: "品質はいかがですか", correct: false },
              { text: "納期はいつですか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "这是我们的最终报价",
            pinyin: "zhè shì wǒmen de zuìzhōng bàojià",
            prompt: "この文の意味は?",
            choices: [
              { text: "これが弊社の最終見積もりです", correct: true },
              { text: "これが今回の契約書です", correct: false },
              { text: "これが最新のカタログです", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我们需要再考虑一下",
            pinyin: "wǒmen xūyào zài kǎolǜ yíxià",
            meaning: "もう少し検討させてください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "見積もり",
            pinyinHint: "bàojià",
            answer: "报价",
          },
          {
            type: "reading",
            passage: "A: 这个价格能不能再便宜一点? B: 这已经是最优惠的价格了。 A: 好的,那我们需要再考虑一下。",
            passagePinyin: "A: Zhège jiàgé néng bùnéng zài piányi yìdiǎn? B: Zhè yǐjīng shì zuì yōuhuì de jiàgé le. A: Hǎo de, nà wǒmen xūyào zài kǎolǜ yíxià.",
            question: "Aさんはどうすると言っていますか?",
            choices: [
              { text: "検討する", correct: true },
              { text: "すぐに契約する", correct: false },
              { text: "取引をやめる", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "我们合作愉快",
            pinyin: "wǒmen hézuò yúkuài",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "良いお取引ができました", correct: true },
              { text: "また今度会いましょう", correct: false },
              { text: "契約は失敗しました", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u8",
    title: "出張と接待",
    description: "ホテル・レストラン接待・ビジネスマナーの表現",
    icon: "✈️",
    lessons: [
      {
        id: "u8l1",
        title: "空港とホテル",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我要办理入住",
            pinyin: "wǒ yào bànlǐ rùzhù",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "チェックインをお願いします", correct: true },
              { text: "チェックアウトをお願いします", correct: false },
              { text: "部屋を予約したいです", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我预订了一个房间",
            pinyin: "wǒ yùdìng le yí gè fángjiān",
            prompt: "この文の意味は?",
            choices: [
              { text: "部屋を一室予約しています", correct: true },
              { text: "部屋を変更したいです", correct: false },
              { text: "部屋は満室です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请问机场怎么走",
            pinyin: "qǐngwèn jīchǎng zěnme zǒu",
            meaning: "空港へはどう行けばいいですか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "チェックインする",
            pinyinHint: "bànlǐ rùzhù",
            answer: "办理入住",
          },
          {
            type: "reading",
            passage: "您好,我姓铃木,预订了一间单人房,今晚入住三晚。",
            passagePinyin: "Nín hǎo, wǒ xìng Língmù, yùdìng le yì jiān dānrénfáng, jīnwǎn rùzhù sān wǎn.",
            question: "何泊予約していますか?",
            choices: [
              { text: "3泊", correct: true },
              { text: "1泊", correct: false },
              { text: "1週間", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "退房时间是几点",
            pinyin: "tuìfáng shíjiān shì jǐ diǎn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "チェックアウトの時間は何時ですか", correct: true },
              { text: "朝食は何時からですか", correct: false },
              { text: "部屋代はいくらですか", correct: false },
            ],
          },
        ],
      },
      {
        id: "u8l2",
        title: "レストランで接待する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "今天我请客",
            pinyin: "jīntiān wǒ qǐngkè",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "今日は私がおごります", correct: true },
              { text: "割り勘にしましょう", correct: false },
              { text: "お腹がすきました", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "请随便点",
            pinyin: "qǐng suíbiàn diǎn",
            prompt: "この文の意味は?",
            choices: [
              { text: "ご自由にご注文ください", correct: true },
              { text: "少々お待ちください", correct: false },
              { text: "辛いものは大丈夫ですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "为我们的合作干杯",
            pinyin: "wèi wǒmen de hézuò gānbēi",
            meaning: "私たちの協力に乾杯しましょう",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "乾杯",
            pinyinHint: "gānbēi",
            answer: "干杯",
          },
          {
            type: "reading",
            passage: "今天晚上我请客,大家想吃什么随便点。为我们的合作干杯!",
            passagePinyin: "Jīntiān wǎnshàng wǒ qǐngkè, dàjiā xiǎng chī shénme suíbiàn diǎn. Wèi wǒmen de hézuò gānbēi!",
            question: "誰がおごりますか?",
            choices: [
              { text: "話している本人", correct: true },
              { text: "部下", correct: false },
              { text: "お客様", correct: false },
            ],
          },
          {
            type: "writing_pinyin",
            hanzi: "合作",
            meaningHint: "協力・提携",
            answer: "hezuo",
            answerToned: "hézuò",
          },
        ],
      },
      {
        id: "u8l3",
        title: "ビジネスマナー",
        exercises: [
          {
            type: "listening_choice",
            audioText: "谢谢您的款待",
            pinyin: "xièxie nín de kuǎndài",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "おもてなしありがとうございました", correct: true },
              { text: "ごちそうさまでした", correct: false },
              { text: "また会いましょう", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "有机会再来北京",
            pinyin: "yǒu jīhuì zài lái Běijīng",
            prompt: "この文の意味は?",
            choices: [
              { text: "機会があればまた北京に来ます", correct: true },
              { text: "また会議をしましょう", correct: false },
              { text: "次は上海に行きます", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "保持联系",
            pinyin: "bǎochí liánxì",
            meaning: "連絡を取り合いましょう",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "連絡を取り合う",
            pinyinHint: "bǎochí liánxì",
            answer: "保持联系",
          },
          {
            type: "reading",
            passage: "这次真的很感谢您的款待。合作很愉快,以后我们保持联系,有机会再来拜访。",
            passagePinyin: "Zhè cì zhēn de hěn gǎnxiè nín de kuǎndài. Hézuò hěn yúkuài, yǐhòu wǒmen bǎochí liánxì, yǒu jīhuì zài lái bàifǎng.",
            question: "この人は今後どうしたいと言っていますか?",
            choices: [
              { text: "連絡を取り続けたい", correct: true },
              { text: "二度と会いたくない", correct: false },
              { text: "契約を終了したい", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "一路平安",
            pinyin: "yílù píng'ān",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "道中お気をつけて", correct: true },
              { text: "おめでとうございます", correct: false },
              { text: "お先に失礼します", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u9",
    title: "プレゼンと報告",
    description: "プレゼン導入・データ説明・質疑応答の表現",
    icon: "📊",
    lessons: [
      {
        id: "u9l1",
        title: "プレゼンを始める",
        exercises: [
          {
            type: "listening_choice",
            audioText: "今天我想跟大家介绍一下新产品",
            pinyin: "jīntiān wǒ xiǎng gēn dàjiā jièshào yíxià xīn chǎnpǐn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "今日は新商品についてご紹介します", correct: true },
              { text: "今日は会議を終わります", correct: false },
              { text: "今日は質問を受け付けます", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "请看这张图表",
            pinyin: "qǐng kàn zhè zhāng túbiǎo",
            prompt: "この文の意味は?",
            choices: [
              { text: "こちらの図表をご覧ください", correct: true },
              { text: "こちらの資料をお配りします", correct: false },
              { text: "こちらの契約書にサインしてください", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "首先,我先说明一下背景",
            pinyin: "shǒuxiān, wǒ xiān shuōmíng yíxià bèijǐng",
            meaning: "まず、背景についてご説明します",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "図表",
            pinyinHint: "túbiǎo",
            answer: "图表",
          },
          {
            type: "reading",
            passage: "大家好,今天我想跟大家介绍一下我们的新产品。首先,请看这张图表。",
            passagePinyin: "Dàjiā hǎo, jīntiān wǒ xiǎng gēn dàjiā jièshào yíxià wǒmen de xīn chǎnpǐn. Shǒuxiān, qǐng kàn zhè zhāng túbiǎo.",
            question: "今日紹介するのは何ですか?",
            choices: [
              { text: "新商品", correct: true },
              { text: "新入社員", correct: false },
              { text: "来年の予算", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "接下来我们看下一页",
            pinyin: "jiē xiàlái wǒmen kàn xià yí yè",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "続いて次のページを見てみましょう", correct: true },
              { text: "これでプレゼンを終わります", correct: false },
              { text: "質問はありますか", correct: false },
            ],
          },
        ],
      },
      {
        id: "u9l2",
        title: "データを説明する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "与去年相比增长了百分之二十",
            pinyin: "yǔ qùnián xiāngbǐ zēngzhǎng le bǎi fēn zhī èrshí",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "去年と比べて20%増加しました", correct: true },
              { text: "去年と比べて20%減少しました", correct: false },
              { text: "去年と同じ水準です", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "销售额比预期高",
            pinyin: "xiāoshòu é bǐ yùqī gāo",
            prompt: "この文の意味は?",
            choices: [
              { text: "売上は予想より高いです", correct: true },
              { text: "売上は予想より低いです", correct: false },
              { text: "売上はまだ発表されていません", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "这是我们的市场占有率",
            pinyin: "zhè shì wǒmen de shìchǎng zhànyǒulǜ",
            meaning: "これが私たちの市場シェアです",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "增长",
            meaningHint: "増加する・伸びる",
            answer: "zengzhang",
            answerToned: "zēngzhǎng",
          },
          {
            type: "reading",
            passage: "今年的销售额与去年相比增长了百分之二十,比我们预期的还要高。",
            passagePinyin: "Jīnnián de xiāoshòu é yǔ qùnián xiāngbǐ zēngzhǎng le bǎi fēn zhī èrshí, bǐ wǒmen yùqī de hái yào gāo.",
            question: "今年の売上はどうでしたか?",
            choices: [
              { text: "予想より20%増加した", correct: true },
              { text: "予想通りだった", correct: false },
              { text: "去年より減少した", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "市場シェア",
            pinyinHint: "shìchǎng zhànyǒulǜ",
            answer: "市场占有率",
          },
        ],
      },
      {
        id: "u9l3",
        title: "質疑応答",
        exercises: [
          {
            type: "listening_choice",
            audioText: "大家有什么问题吗",
            pinyin: "dàjiā yǒu shénme wèntí ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "皆さん何か質問はありますか", correct: true },
              { text: "皆さん賛成ですか", correct: false },
              { text: "皆さん資料は届きましたか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "关于这一点我再补充一下",
            pinyin: "guānyú zhè yìdiǎn wǒ zài bǔchōng yíxià",
            prompt: "この文の意味は?",
            choices: [
              { text: "この点について補足させてください", correct: true },
              { text: "この点についてはわかりません", correct: false },
              { text: "この点は後日回答します", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "谢谢大家的提问",
            pinyin: "xièxie dàjiā de tíwèn",
            meaning: "ご質問ありがとうございます",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "補足する",
            pinyinHint: "bǔchōng",
            answer: "补充",
          },
          {
            type: "reading",
            passage: "A: 请问这个产品什么时候上市? B: 关于这一点我再补充一下,预计下个月上市。",
            passagePinyin: "A: Qǐngwèn zhège chǎnpǐn shénme shíhou shàngshì? B: Guānyú zhè yìdiǎn wǒ zài bǔchōng yíxià, yùjì xià ge yuè shàngshì.",
            question: "商品はいつ発売される予定ですか?",
            choices: [
              { text: "来月", correct: true },
              { text: "今月", correct: false },
              { text: "来年", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "这个问题我需要确认一下",
            pinyin: "zhège wèntí wǒ xūyào quèrèn yíxià",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "この質問は確認させてください", correct: true },
              { text: "この質問には答えられません", correct: false },
              { text: "この質問はもう回答しました", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u10",
    title: "クレーム対応とトラブル",
    description: "謝罪・問題説明・解決策の提示",
    icon: "🛠️",
    lessons: [
      {
        id: "u10l1",
        title: "謝罪する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "非常抱歉给您带来不便",
            pinyin: "fēicháng bàoqiàn gěi nín dàilái búbiàn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "ご不便をおかけして大変申し訳ございません", correct: true },
              { text: "ご連絡ありがとうございます", correct: false },
              { text: "少々お待ちください", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "这是我们的失误",
            pinyin: "zhè shì wǒmen de shīwù",
            prompt: "この文の意味は?",
            choices: [
              { text: "これは私たちのミスです", correct: true },
              { text: "これはお客様の勘違いです", correct: false },
              { text: "これはよくあることです", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我们会尽快处理",
            pinyin: "wǒmen huì jǐnkuài chǔlǐ",
            meaning: "至急対応いたします",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "ミス・失策",
            pinyinHint: "shīwù",
            answer: "失误",
          },
          {
            type: "reading",
            passage: "非常抱歉给您带来不便,这是我们的失误,我们会尽快处理。",
            passagePinyin: "Fēicháng bàoqiàn gěi nín dàilái búbiàn, zhè shì wǒmen de shīwù, wǒmen huì jǐnkuài chǔlǐ.",
            question: "話し手はこの問題を誰の責任だと言っていますか?",
            choices: [
              { text: "自分たち(自社)", correct: true },
              { text: "お客様", correct: false },
              { text: "配送業者", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "给您添麻烦了",
            pinyin: "gěi nín tiān máfan le",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "ご面倒をおかけしました", correct: true },
              { text: "ありがとうございました", correct: false },
              { text: "お待たせしました", correct: false },
            ],
          },
        ],
      },
      {
        id: "u10l2",
        title: "問題を説明する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "产品出现了质量问题",
            pinyin: "chǎnpǐn chūxiàn le zhìliàng wèntí",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "製品に品質の問題が発生しました", correct: true },
              { text: "製品は問題なく届きました", correct: false },
              { text: "製品の在庫がありません", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "交货延迟了三天",
            pinyin: "jiāohuò yánchí le sān tiān",
            prompt: "この文の意味は?",
            choices: [
              { text: "納品が3日遅れました", correct: true },
              { text: "納品が3日早まりました", correct: false },
              { text: "納品は3日後の予定です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我们需要更换零件",
            pinyin: "wǒmen xūyào gēnghuàn língjiàn",
            meaning: "部品を交換する必要があります",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "延迟",
            meaningHint: "遅延する",
            answer: "yanchi",
            answerToned: "yánchí",
          },
          {
            type: "reading",
            passage: "很抱歉,这次交货延迟了三天,原因是产品出现了质量问题,我们需要更换零件。",
            passagePinyin: "Hěn bàoqiàn, zhè cì jiāohuò yánchí le sān tiān, yuányīn shì chǎnpǐn chūxiàn le zhìliàng wèntí, wǒmen xūyào gēnghuàn língjiàn.",
            question: "納品が遅れた原因は何ですか?",
            choices: [
              { text: "品質問題で部品交換が必要になったから", correct: true },
              { text: "注文数が多すぎたから", correct: false },
              { text: "配送業者の休業", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "部品",
            pinyinHint: "língjiàn",
            answer: "零件",
          },
        ],
      },
      {
        id: "u10l3",
        title: "解決策を提示する",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我们可以退款",
            pinyin: "wǒmen kěyǐ tuìkuǎn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "返金することができます", correct: true },
              { text: "返品はできません", correct: false },
              { text: "交換は可能です", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我们会重新发货",
            pinyin: "wǒmen huì chóngxīn fāhuò",
            prompt: "この文の意味は?",
            choices: [
              { text: "改めて発送いたします", correct: true },
              { text: "注文をキャンセルします", correct: false },
              { text: "在庫を確認します", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请给我们一次机会",
            pinyin: "qǐng gěi wǒmen yí cì jīhuì",
            meaning: "もう一度機会をいただけますでしょうか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "返金する",
            pinyinHint: "tuìkuǎn",
            answer: "退款",
          },
          {
            type: "reading",
            passage: "对于这次的问题,我们会重新发货,或者为您退款。请给我们一次机会,以后一定会改进。",
            passagePinyin: "Duìyú zhè cì de wèntí, wǒmen huì chóngxīn fāhuò, huòzhě wèi nín tuìkuǎn. Qǐng gěi wǒmen yí cì jīhuì, yǐhòu yídìng huì gǎijìn.",
            question: "会社が提示している解決策は?",
            choices: [
              { text: "再発送または返金", correct: true },
              { text: "値引きのみ", correct: false },
              { text: "何もしない", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "以后一定会改进",
            pinyin: "yǐhòu yídìng huì gǎijìn",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "今後は必ず改善いたします", correct: true },
              { text: "今後もこのままです", correct: false },
              { text: "改善する予定はありません", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u11",
    title: "人事と採用",
    description: "面接・職場の人間関係・キャリアの表現",
    icon: "🧑‍💼",
    lessons: [
      {
        id: "u11l1",
        title: "面接を受ける",
        exercises: [
          {
            type: "listening_choice",
            audioText: "请做一下自我介绍",
            pinyin: "qǐng zuò yíxià zìwǒ jièshào",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "自己紹介をしてください", correct: true },
              { text: "名刺をください", correct: false },
              { text: "履歴書を提出してください", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "您的优点是什么",
            pinyin: "nín de yōudiǎn shì shénme",
            prompt: "この文の意味は?",
            choices: [
              { text: "あなたの長所は何ですか", correct: true },
              { text: "あなたの欠点は何ですか", correct: false },
              { text: "あなたの経験は何ですか", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "为什么想加入我们公司",
            pinyin: "wèishénme xiǎng jiārù wǒmen gōngsī",
            meaning: "なぜ弊社に入社したいのですか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "長所",
            pinyinHint: "yōudiǎn",
            answer: "优点",
          },
          {
            type: "reading",
            passage: "请做一下自我介绍,并说说您的优点是什么,为什么想加入我们公司。",
            passagePinyin: "Qǐng zuò yíxià zìwǒ jièshào, bìng shuōshuo nín de yōudiǎn shì shénme, wèishénme xiǎng jiārù wǒmen gōngsī.",
            question: "この文章は何の場面ですか?",
            choices: [
              { text: "採用面接", correct: true },
              { text: "顧客訪問", correct: false },
              { text: "取引先との会議", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "您有什么想问我们的吗",
            pinyin: "nín yǒu shénme xiǎng wèn wǒmen de ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "私たちに何か質問はありますか", correct: true },
              { text: "いつから働けますか", correct: false },
              { text: "給料はいくら希望ですか", correct: false },
            ],
          },
        ],
      },
      {
        id: "u11l2",
        title: "職場の人間関係",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我们部门有十个人",
            pinyin: "wǒmen bùmén yǒu shí ge rén",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "私たちの部署は10人です", correct: true },
              { text: "私たちの会社は10人です", correct: false },
              { text: "会議には10人来ます", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我的上司很严格",
            pinyin: "wǒ de shàngsi hěn yángé",
            prompt: "この文の意味は?",
            choices: [
              { text: "私の上司はとても厳しいです", correct: true },
              { text: "私の上司はとても優しいです", correct: false },
              { text: "私には上司がいません", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "同事之间关系很好",
            pinyin: "tóngshì zhījiān guānxi hěn hǎo",
            meaning: "同僚同士の関係は良好です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "上司",
            meaningHint: "上司",
            answer: "shangsi",
            answerToned: "shàngsi",
          },
          {
            type: "reading",
            passage: "我们部门有十个人,我的上司很严格,不过同事之间关系很好,大家互相帮助。",
            passagePinyin: "Wǒmen bùmén yǒu shí ge rén, wǒ de shàngsi hěn yángé, búguò tóngshì zhījiān guānxi hěn hǎo, dàjiā hùxiāng bāngzhù.",
            question: "同僚同士の関係はどうですか?",
            choices: [
              { text: "良好", correct: true },
              { text: "悪い", correct: false },
              { text: "文章からはわからない", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "同僚",
            pinyinHint: "tóngshì",
            answer: "同事",
          },
        ],
      },
      {
        id: "u11l3",
        title: "キャリアについて話す",
        exercises: [
          {
            type: "listening_choice",
            audioText: "我想升职",
            pinyin: "wǒ xiǎng shēngzhí",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "昇進したいです", correct: true },
              { text: "転職したいです", correct: false },
              { text: "退職したいです", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "这是一个很好的机会",
            pinyin: "zhè shì yí gè hěn hǎo de jīhuì",
            prompt: "この文の意味は?",
            choices: [
              { text: "これはとても良い機会です", correct: true },
              { text: "これは難しい問題です", correct: false },
              { text: "これは重要な会議です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "我打算换工作",
            pinyin: "wǒ dǎsuàn huàn gōngzuò",
            meaning: "転職しようと思っています",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "昇進する",
            pinyinHint: "shēngzhí",
            answer: "升职",
          },
          {
            type: "reading",
            passage: "我在这家公司工作了五年,现在我想升职,或者考虑换工作,这对我来说是一个很好的机会。",
            passagePinyin: "Wǒ zài zhè jiā gōngsī gōngzuò le wǔ nián, xiànzài wǒ xiǎng shēngzhí, huòzhě kǎolǜ huàn gōngzuò, zhè duì wǒ lái shuō shì yí gè hěn hǎo de jīhuì.",
            question: "この人はどれくらいこの会社で働いていますか?",
            choices: [
              { text: "5年", correct: true },
              { text: "1年", correct: false },
              { text: "10年", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "祝贺你升职",
            pinyin: "zhùhè nǐ shēngzhí",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "昇進おめでとうございます", correct: true },
              { text: "退職おめでとうございます", correct: false },
              { text: "入社おめでとうございます", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u12",
    title: "契約とビジネス文書",
    description: "契約の基本・支払い納期・正式な依頼の表現",
    icon: "📄",
    lessons: [
      {
        id: "u12l1",
        title: "契約の基本",
        exercises: [
          {
            type: "listening_choice",
            audioText: "请在这里签字",
            pinyin: "qǐng zài zhèlǐ qiānzì",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "こちらにご署名ください", correct: true },
              { text: "こちらにご記入ください", correct: false },
              { text: "こちらをご確認ください", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "合同有效期是一年",
            pinyin: "hétong yǒuxiàoqī shì yì nián",
            prompt: "この文の意味は?",
            choices: [
              { text: "契約の有効期間は1年です", correct: true },
              { text: "契約はまだ締結していません", correct: false },
              { text: "契約は今月で終了します", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "请仔细阅读条款",
            pinyin: "qǐng zǐxì yuèdú tiáokuǎn",
            meaning: "条項をよくお読みください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "契約書",
            pinyinHint: "hétong",
            answer: "合同",
          },
          {
            type: "reading",
            passage: "这是我们的合同,有效期是一年。请仔细阅读条款,如果没有问题,请在这里签字。",
            passagePinyin: "Zhè shì wǒmen de hétong, yǒuxiàoqī shì yì nián. Qǐng zǐxì yuèdú tiáokuǎn, rúguǒ méiyǒu wèntí, qǐng zài zhèlǐ qiānzì.",
            question: "契約の有効期間はどれくらいですか?",
            choices: [
              { text: "1年", correct: true },
              { text: "半年", correct: false },
              { text: "3年", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "这份合同可以修改吗",
            pinyin: "zhè fèn hétong kěyǐ xiūgǎi ma",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "この契約書は修正できますか", correct: true },
              { text: "この契約書はもう無効です", correct: false },
              { text: "この契約書はコピーできますか", correct: false },
            ],
          },
        ],
      },
      {
        id: "u12l2",
        title: "支払いと納期",
        exercises: [
          {
            type: "listening_choice",
            audioText: "付款方式是什么",
            pinyin: "fùkuǎn fāngshì shì shénme",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "お支払い方法は何ですか", correct: true },
              { text: "納期はいつですか", correct: false },
              { text: "金額はいくらですか", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "我们分期付款",
            pinyin: "wǒmen fēnqī fùkuǎn",
            prompt: "この文の意味は?",
            choices: [
              { text: "分割払いにします", correct: true },
              { text: "一括払いにします", correct: false },
              { text: "前払いにします", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "交货日期是几号",
            pinyin: "jiāohuò rìqī shì jǐ hào",
            meaning: "納品日は何日ですか",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "付款",
            meaningHint: "支払う",
            answer: "fukuan",
            answerToned: "fùkuǎn",
          },
          {
            type: "reading",
            passage: "A: 付款方式是什么? B: 我们分期付款,分三次支付。 A: 好的,那交货日期是几号?",
            passagePinyin: "A: Fùkuǎn fāngshì shì shénme? B: Wǒmen fēnqī fùkuǎn, fēn sān cì zhīfù. A: Hǎo de, nà jiāohuò rìqī shì jǐ hào?",
            question: "支払いは何回に分けますか?",
            choices: [
              { text: "3回", correct: true },
              { text: "1回", correct: false },
              { text: "5回", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "納品日",
            pinyinHint: "jiāohuò rìqī",
            answer: "交货日期",
          },
        ],
      },
      {
        id: "u12l3",
        title: "正式な依頼・確認",
        exercises: [
          {
            type: "listening_choice",
            audioText: "麻烦您确认一下",
            pinyin: "máfan nín quèrèn yíxià",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "ご確認をお願いいたします", correct: true },
              { text: "少々お待ちください", correct: false },
              { text: "ご迷惑をおかけしました", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "请尽快回复我们",
            pinyin: "qǐng jǐnkuài huífù wǒmen",
            prompt: "この文の意味は?",
            choices: [
              { text: "至急ご返信ください", correct: true },
              { text: "ゆっくりご検討ください", correct: false },
              { text: "返信は不要です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "如有任何问题请联系我们",
            pinyin: "rú yǒu rènhé wèntí qǐng liánxì wǒmen",
            meaning: "何かご不明な点がございましたらご連絡ください",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "至急・できるだけ早く",
            pinyinHint: "jǐnkuài",
            answer: "尽快",
          },
          {
            type: "reading",
            passage: "麻烦您确认一下附件中的报价单,如有任何问题请联系我们,并请尽快回复。",
            passagePinyin: "Máfan nín quèrèn yíxià fùjiàn zhōng de bàojiàdān, rú yǒu rènhé wèntí qǐng liánxì wǒmen, bìng qǐng jǐnkuài huífù.",
            question: "相手に依頼している内容は?",
            choices: [
              { text: "見積書の確認と早めの返信", correct: true },
              { text: "契約書へのサイン", correct: false },
              { text: "会議日程の調整", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "感谢您一直以来的支持",
            pinyin: "gǎnxiè nín yìzhí yǐlái de zhīchí",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "いつもご支援いただきありがとうございます", correct: true },
              { text: "初めまして、よろしくお願いします", correct: false },
              { text: "契約解除のご連絡です", correct: false },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "u13",
    title: "契約書とコンプライアンス",
    description: "業務委託契約書の読み方・報酬・解除条項の表現",
    icon: "⚖️",
    lessons: [
      {
        id: "u13l1",
        title: "契約の基本条項",
        exercises: [
          {
            type: "listening_choice",
            audioText: "甲方委托乙方开发系统",
            pinyin: "jiǎfāng wěituō yǐfāng kāifā xìtǒng",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "甲は乙にシステム開発を委託する", correct: true },
              { text: "甲は乙からシステムを購入する", correct: false },
              { text: "甲と乙は共同でシステムを開発する", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "这是一份准委任合同",
            pinyin: "zhè shì yí fèn zhǔn wěirèn hétong",
            prompt: "この文の意味は?",
            choices: [
              { text: "これは準委任契約です", correct: true },
              { text: "これは雇用契約です", correct: false },
              { text: "これは売買契約です", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "乙方需要遵守善良管理人的注意义务",
            pinyin: "yǐfāng xūyào zūnshǒu shànliáng guǎnlǐrén de zhùyì yìwù",
            meaning: "乙は善管注意義務を遵守する必要があります",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "知的財産権",
            pinyinHint: "zhīshi chǎnquán",
            answer: "知识产权",
          },
          {
            type: "reading",
            passage: "本合同的目的是甲方委托乙方进行系统开发业务。双方确认本合同为准委任合同。",
            passagePinyin: "Běn hétong de mùdì shì jiǎfāng wěituō yǐfāng jìnxíng xìtǒng kāifā yèwù. Shuāngfāng quèrèn běn hétong wéi zhǔn wěirèn hétong.",
            question: "この契約の性質は何ですか?",
            choices: [
              { text: "準委任契約", correct: true },
              { text: "雇用契約", correct: false },
              { text: "売買契約", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "乙方享有业务执行的自由裁量权",
            pinyin: "yǐfāng xiǎngyǒu yèwù zhíxíng de zìyóu cáiliàngquán",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "乙は業務遂行について裁量権を持つ", correct: true },
              { text: "甲は乙の業務時間を管理する", correct: false },
              { text: "乙は毎日出社する必要がある", correct: false },
            ],
          },
        ],
      },
      {
        id: "u13l2",
        title: "報酬と支払い",
        exercises: [
          {
            type: "listening_choice",
            audioText: "月度业务委托费为一百万日元",
            pinyin: "yuèdù yèwù wěituō fèi wéi yìbǎiwàn rìyuán",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "月額の業務委託料は100万円です", correct: true },
              { text: "年収は100万円です", correct: false },
              { text: "契約金は10万円です", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "费用按日计算",
            pinyin: "fèiyòng àn rì jìsuàn",
            prompt: "この文の意味は?",
            choices: [
              { text: "費用は日割りで計算されます", correct: true },
              { text: "費用は月末に一括請求されます", correct: false },
              { text: "費用は前払いです", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "乙方需要每月提交业务报告书",
            pinyin: "yǐfāng xūyào měi yuè tíjiāo yèwù bàogàoshū",
            meaning: "乙は毎月業務報告書を提出する必要があります",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_pinyin",
            hanzi: "请求书",
            meaningHint: "請求書",
            answer: "qingqiushu",
            answerToned: "qǐngqiúshū",
          },
          {
            type: "reading",
            passage: "乙方每月提交业务报告书及请求书,甲方确认后于次月末支付费用。汇款手续费由甲方承担。",
            passagePinyin: "Yǐfāng měi yuè tíjiāo yèwù bàogàoshū jí qǐngqiúshū, jiǎfāng quèrèn hòu yú cì yuè mò zhīfù fèiyòng. Huìkuǎn shǒuxùfèi yóu jiǎfāng chéngdān.",
            question: "振込手数料は誰が負担しますか?",
            choices: [
              { text: "甲(発注者)", correct: true },
              { text: "乙(受注者)", correct: false },
              { text: "双方で折半", correct: false },
            ],
          },
          {
            type: "writing_cn",
            meaning: "減額する",
            pinyinHint: "jiǎn'é",
            answer: "减额",
          },
        ],
      },
      {
        id: "u13l3",
        title: "契約解除・競業避止",
        exercises: [
          {
            type: "listening_choice",
            audioText: "任何一方均可提前三十天书面通知解除合同",
            pinyin: "rènhé yì fāng jūn kě tíqián sānshí tiān shūmiàn tōngzhī jiěchú hétong",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "どちらの当事者も30日前の書面通知で解約できる", correct: true },
              { text: "契約は途中解約できない", correct: false },
              { text: "契約解除には裁判所の許可が必要", correct: false },
            ],
          },
          {
            type: "translate_choice",
            hanzi: "乙方负有竞业避止义务",
            pinyin: "yǐfāng fùyǒu jìngyè bìzhǐ yìwù",
            prompt: "この文の意味は?",
            choices: [
              { text: "乙は競業避止義務を負います", correct: true },
              { text: "乙は秘密保持義務を負いません", correct: false },
              { text: "乙は自由に転職できます", correct: false },
            ],
          },
          {
            type: "speaking",
            hanzi: "损害赔偿的上限为业务委托费的总额",
            pinyin: "sǔnhài péicháng de shàngxiàn wéi yèwù wěituō fèi de zǒng'é",
            meaning: "損害賠償の上限は業務委託料の総額です",
            prompt: "声に出して発音してみましょう",
          },
          {
            type: "writing_cn",
            meaning: "反社会的勢力",
            pinyinHint: "fǎnshèhuì shìlì",
            answer: "反社会势力",
          },
          {
            type: "reading",
            passage: "如果乙方违反竞业避止义务或保密义务,损害赔偿金额不受上限限制。",
            passagePinyin: "Rúguǒ yǐfāng wéifǎn jìngyè bìzhǐ yìwù huò bǎomì yìwù, sǔnhài péicháng jīn'é bú shòu shàngxiàn xiànzhì.",
            question: "上限が適用されないケースはどれですか?",
            choices: [
              { text: "競業避止義務・秘密保持義務違反", correct: true },
              { text: "軽微な報告遅延", correct: false },
              { text: "すべての違反に上限が適用される", correct: false },
            ],
          },
          {
            type: "listening_choice",
            audioText: "本合同可因故意或重大过失而解除",
            pinyin: "běn hétong kě yīn gùyì huò zhòngdà guòshī ér jiěchú",
            prompt: "今聞こえた文の意味はどれ?",
            choices: [
              { text: "故意または重大な過失により契約を解除できる", correct: true },
              { text: "過失があっても契約は解除できない", correct: false },
              { text: "合意がなければ解除できない", correct: false },
            ],
          },
        ],
      },
    ],
  },
];

// レベルロードマップ: ユニットをHSKに対応する段階にまとめ、
// 「ビジネス中国語が話せる」ゴールまでの距離を可視化する。
// targetVocab / targetHours は旧HSK1〜6の公表語彙数(累計150/300/600/
// 1200/2500/5000語)と、FSIなど言語難易度研究で目安とされる英語話者の
// 中国語習得時間(カテゴリー最難関言語で累計2,000〜2,500時間程度)を
// もとにした概算。あくまで目安であり、アプリ内の学習だけで到達できる
// 数字ではない点をUI上で明示する。
const LEVELS = [
  {
    id: "lv1",
    label: "Lv.1 入門",
    hskLabel: "HSK1相当",
    unitIds: ["u1", "u2"],
    description: "あいさつ・数字など基本のフレーズが言える",
    implemented: true,
    targetVocab: 150,
    targetHours: 100,
  },
  {
    id: "lv2",
    label: "Lv.2 初級",
    hskLabel: "HSK2相当",
    unitIds: ["u3", "u4"],
    description: "家族・日常生活について簡単な会話ができる",
    implemented: true,
    targetVocab: 300,
    targetHours: 250,
  },
  {
    id: "lv3",
    label: "Lv.3 中級",
    hskLabel: "HSK3相当",
    unitIds: ["u5", "u6"],
    description: "職業紹介・電話やメールなど仕事の基本連絡ができる",
    implemented: true,
    targetVocab: 600,
    targetHours: 500,
  },
  {
    id: "lv4",
    label: "Lv.4 中級上",
    hskLabel: "HSK4相当",
    unitIds: ["u7", "u8"],
    description: "会議・交渉・接待などビジネスの基本場面に対応できる",
    implemented: true,
    targetVocab: 1200,
    targetHours: 900,
  },
  {
    id: "lv5",
    label: "Lv.5 上級",
    hskLabel: "HSK5相当",
    unitIds: ["u9", "u10"],
    description: "プレゼン・報告・クレーム対応など複雑な議論ができる",
    implemented: true,
    targetVocab: 2500,
    targetHours: 1500,
  },
  {
    id: "lv6",
    label: "Lv.6 ビジネス実務",
    hskLabel: "HSK6相当",
    unitIds: ["u11", "u12", "u13"],
    description: "ゴール: 採用面接・契約書対応など通訳なしでビジネス実務を主導できる",
    implemented: true,
    targetVocab: 5000,
    targetHours: 2500,
  },
];

const GOAL_LEVEL_ID = "lv6";

// ロードマップ画面に表示する、目安数値の根拠に関する注記
const LEVEL_BENCHMARK_NOTE =
  "語彙数は旧HSK1〜6の公表基準(累計150/300/600/1200/2500/5000語)、学習時間は言語難易度研究(FSI等)で中国語の目安とされる累計時間を参考にした概算です。個人差が大きく、アプリ内の学習だけで到達できる数字ではありません。";

// スキル(4技能)のメタ情報
const SKILLS = {
  listening: { label: "リスニング", icon: "👂", color: "#1cb0f6" },
  speaking: { label: "スピーキング", icon: "🗣️", color: "#ff4b4b" },
  reading: { label: "リーディング", icon: "📖", color: "#ce82ff" },
  writing: { label: "ライティング", icon: "✍️", color: "#ffc800" },
};

// エクササイズタイプ → スキルの対応
const EXERCISE_SKILL = {
  listening_choice: "listening",
  speaking: "speaking",
  reading: "reading",
  translate_choice: "reading",
  writing_cn: "writing",
  writing_pinyin: "writing",
};
