// 単語カード(フラッシュカード)用の語彙データ。
// 電車移動中など短時間でもサクサク復習できるよう、レッスンとは別の
// 「単語帳」モードで使う。分野特化(貿易・輸出 / 会計・税務)の実務語彙。
//
// 注: 「10,000語」規模は正確さを保証できる量ではないため、まずは
// 実務でよく使う語を厳選して収録している(合計200語)。今後のアップデートで
// 追加していく前提のデータ構造になっている。

const VOCAB_DECKS = [
  {
    id: "trade",
    label: "貿易・輸出",
    icon: "📦",
    description: "日本から中国への輸出・貿易実務でよく使う単語",
    words: [
      { hanzi: "出口", pinyin: "chūkǒu", meaning: "輸出" },
      { hanzi: "进口", pinyin: "jìnkǒu", meaning: "輸入" },
      { hanzi: "贸易", pinyin: "màoyì", meaning: "貿易" },
      { hanzi: "合同", pinyin: "hétong", meaning: "契約書" },
      { hanzi: "报关", pinyin: "bàoguān", meaning: "通関(申告)" },
      { hanzi: "关税", pinyin: "guānshuì", meaning: "関税" },
      { hanzi: "海关", pinyin: "hǎiguān", meaning: "税関" },
      { hanzi: "集装箱", pinyin: "jízhuāngxiāng", meaning: "コンテナ" },
      { hanzi: "提单", pinyin: "tídān", meaning: "船荷証券(B/L)" },
      { hanzi: "信用证", pinyin: "xìnyòngzhèng", meaning: "信用状(L/C)" },
      { hanzi: "装运", pinyin: "zhuāngyùn", meaning: "船積み" },
      { hanzi: "运费", pinyin: "yùnfèi", meaning: "運賃" },
      { hanzi: "报价单", pinyin: "bàojiàdān", meaning: "見積書" },
      { hanzi: "订单", pinyin: "dìngdān", meaning: "注文書" },
      { hanzi: "采购", pinyin: "cǎigòu", meaning: "仕入れ・調達" },
      { hanzi: "供应商", pinyin: "gōngyìngshāng", meaning: "サプライヤー" },
      { hanzi: "买方", pinyin: "mǎifāng", meaning: "買主" },
      { hanzi: "卖方", pinyin: "màifāng", meaning: "売主" },
      { hanzi: "原产地证明", pinyin: "yuánchǎndì zhèngmíng", meaning: "原産地証明書" },
      { hanzi: "装箱单", pinyin: "zhuāngxiāngdān", meaning: "パッキングリスト" },
      { hanzi: "发票", pinyin: "fāpiào", meaning: "インボイス・領収書" },
      { hanzi: "商检", pinyin: "shāngjiǎn", meaning: "商品検査" },
      { hanzi: "质检", pinyin: "zhìjiǎn", meaning: "品質検査" },
      { hanzi: "港口", pinyin: "gǎngkǒu", meaning: "港" },
      { hanzi: "码头", pinyin: "mǎtóu", meaning: "埠頭" },
      { hanzi: "船公司", pinyin: "chuán gōngsī", meaning: "船会社" },
      { hanzi: "空运", pinyin: "kōngyùn", meaning: "航空輸送" },
      { hanzi: "海运", pinyin: "hǎiyùn", meaning: "海上輸送" },
      { hanzi: "陆运", pinyin: "lùyùn", meaning: "陸上輸送" },
      { hanzi: "保税区", pinyin: "bǎoshuìqū", meaning: "保税区" },
      { hanzi: "清关", pinyin: "qīngguān", meaning: "通関手続き" },
      { hanzi: "关税税率", pinyin: "guānshuì shuìlǜ", meaning: "関税率" },
      { hanzi: "出口退税", pinyin: "chūkǒu tuìshuì", meaning: "輸出戻し税" },
      { hanzi: "汇率", pinyin: "huìlǜ", meaning: "為替レート" },
      { hanzi: "外汇", pinyin: "wàihuì", meaning: "外貨" },
      { hanzi: "结汇", pinyin: "jiéhuì", meaning: "為替決済" },
      { hanzi: "电汇", pinyin: "diànhuì", meaning: "電信送金(T/T)" },
      { hanzi: "预付款", pinyin: "yùfùkuǎn", meaning: "前払金" },
      { hanzi: "尾款", pinyin: "wěikuǎn", meaning: "残金" },
      { hanzi: "交货期", pinyin: "jiāohuò qī", meaning: "納期" },
      { hanzi: "样品", pinyin: "yàngpǐn", meaning: "サンプル" },
      { hanzi: "批量生产", pinyin: "pīliàng shēngchǎn", meaning: "量産" },
      { hanzi: "最小起订量", pinyin: "zuìxiǎo qǐdìngliàng", meaning: "最小発注数量(MOQ)" },
      { hanzi: "供应链", pinyin: "gōngyìngliàn", meaning: "サプライチェーン" },
      { hanzi: "库存", pinyin: "kùcún", meaning: "在庫" },
      { hanzi: "仓库", pinyin: "cāngkù", meaning: "倉庫" },
      { hanzi: "物流", pinyin: "wùliú", meaning: "物流" },
      { hanzi: "承运人", pinyin: "chéngyùnrén", meaning: "運送人" },
      { hanzi: "报关行", pinyin: "bàoguānháng", meaning: "通関業者" },
      { hanzi: "出口许可证", pinyin: "chūkǒu xǔkězhèng", meaning: "輸出許可証" },
      { hanzi: "进口关税", pinyin: "jìnkǒu guānshuì", meaning: "輸入関税" },
      { hanzi: "增值税", pinyin: "zēngzhíshuì", meaning: "増値税(VAT)" },
      { hanzi: "保险单", pinyin: "bǎoxiǎndān", meaning: "保険証券" },
      { hanzi: "提货", pinyin: "tíhuò", meaning: "貨物の引き取り" },
      { hanzi: "卸货", pinyin: "xièhuò", meaning: "荷降ろし" },
      { hanzi: "装货", pinyin: "zhuānghuò", meaning: "積み込み" },
      { hanzi: "货物", pinyin: "huòwù", meaning: "貨物" },
      { hanzi: "重量", pinyin: "zhòngliàng", meaning: "重量" },
      { hanzi: "体积", pinyin: "tǐjī", meaning: "体積" },
      { hanzi: "单价", pinyin: "dānjià", meaning: "単価" },
      { hanzi: "总价", pinyin: "zǒngjià", meaning: "合計金額" },
      { hanzi: "折扣", pinyin: "zhékòu", meaning: "割引" },
      { hanzi: "付款条件", pinyin: "fùkuǎn tiáojiàn", meaning: "支払条件" },
      { hanzi: "交易条款", pinyin: "jiāoyì tiáokuǎn", meaning: "取引条件" },
      { hanzi: "违约金", pinyin: "wéiyuējīn", meaning: "違約金" },
      { hanzi: "索赔", pinyin: "suǒpéi", meaning: "クレーム・損害賠償請求" },
      { hanzi: "退货", pinyin: "tuìhuò", meaning: "返品" },
      { hanzi: "换货", pinyin: "huànhuò", meaning: "交換" },
      { hanzi: "保修期", pinyin: "bǎoxiūqī", meaning: "保証期間" },
      { hanzi: "代理商", pinyin: "dàilǐshāng", meaning: "代理店" },
      { hanzi: "经销商", pinyin: "jīngxiāoshāng", meaning: "ディストリビューター" },
      { hanzi: "展会", pinyin: "zhǎnhuì", meaning: "展示会" },
      { hanzi: "询盘", pinyin: "xúnpán", meaning: "引き合い" },
      { hanzi: "报盘", pinyin: "bàopán", meaning: "オファー(売り申込み)" },
      { hanzi: "还盘", pinyin: "huánpán", meaning: "カウンターオファー" },
      { hanzi: "成交", pinyin: "chéngjiāo", meaning: "成約" },
      { hanzi: "商标", pinyin: "shāngbiāo", meaning: "商標" },
      { hanzi: "专利", pinyin: "zhuānlì", meaning: "特許" },
      { hanzi: "知识产权", pinyin: "zhīshi chǎnquán", meaning: "知的財産権" },
      { hanzi: "原材料", pinyin: "yuáncáiliào", meaning: "原材料" },
      { hanzi: "成品", pinyin: "chéngpǐn", meaning: "完成品" },
      { hanzi: "半成品", pinyin: "bànchéngpǐn", meaning: "半製品" },
      { hanzi: "生产厂家", pinyin: "shēngchǎn chǎngjiā", meaning: "メーカー" },
      { hanzi: "质量标准", pinyin: "zhìliàng biāozhǔn", meaning: "品質基準" },
      { hanzi: "认证", pinyin: "rènzhèng", meaning: "認証" },
      { hanzi: "检验报告", pinyin: "jiǎnyàn bàogào", meaning: "検査報告書" },
      { hanzi: "关务", pinyin: "guānwù", meaning: "通関業務" },
      { hanzi: "自由贸易协定", pinyin: "zìyóu màoyì xiédìng", meaning: "自由貿易協定(FTA)" },
      { hanzi: "关税同盟", pinyin: "guānshuì tóngméng", meaning: "関税同盟" },
      { hanzi: "出口商", pinyin: "chūkǒushāng", meaning: "輸出業者" },
      { hanzi: "进口商", pinyin: "jìnkǒushāng", meaning: "輸入業者" },
      { hanzi: "集装箱码头", pinyin: "jízhuāngxiāng mǎtóu", meaning: "コンテナヤード" },
      { hanzi: "提货单", pinyin: "tíhuòdān", meaning: "荷渡指図書(D/O)" },
      { hanzi: "商业发票", pinyin: "shāngyè fāpiào", meaning: "商業送り状" },
      { hanzi: "汇款", pinyin: "huìkuǎn", meaning: "送金" },
      { hanzi: "银行手续费", pinyin: "yínháng shǒuxùfèi", meaning: "銀行手数料" },
      { hanzi: "贸易顺差", pinyin: "màoyì shùnchā", meaning: "貿易黒字" },
      { hanzi: "贸易逆差", pinyin: "màoyì nìchā", meaning: "貿易赤字" },
      { hanzi: "关税壁垒", pinyin: "guānshuì bìlěi", meaning: "関税障壁" },
      { hanzi: "出口配额", pinyin: "chūkǒu pèi'é", meaning: "輸出割当" },
    ],
  },
  {
    id: "accounting",
    label: "会計・税務",
    icon: "🧾",
    description: "中国現地法人・取引先とのやり取りで使う会計・税務用語",
    words: [
      { hanzi: "会计", pinyin: "kuàijì", meaning: "会計" },
      { hanzi: "财务", pinyin: "cáiwù", meaning: "財務" },
      { hanzi: "税务", pinyin: "shuìwù", meaning: "税務" },
      { hanzi: "所得税", pinyin: "suǒdéshuì", meaning: "所得税" },
      { hanzi: "企业所得税", pinyin: "qǐyè suǒdéshuì", meaning: "法人税" },
      { hanzi: "个人所得税", pinyin: "gèrén suǒdéshuì", meaning: "個人所得税" },
      { hanzi: "增值税发票", pinyin: "zēngzhíshuì fāpiào", meaning: "増値税専用発票" },
      { hanzi: "税率", pinyin: "shuìlǜ", meaning: "税率" },
      { hanzi: "纳税人", pinyin: "nàshuìrén", meaning: "納税者" },
      { hanzi: "纳税申报", pinyin: "nàshuì shēnbào", meaning: "納税申告" },
      { hanzi: "报税", pinyin: "bàoshuì", meaning: "税務申告(する)" },
      { hanzi: "税务局", pinyin: "shuìwùjú", meaning: "税務局" },
      { hanzi: "审计", pinyin: "shěnjì", meaning: "監査" },
      { hanzi: "会计师", pinyin: "kuàijìshī", meaning: "会計士" },
      { hanzi: "注册会计师", pinyin: "zhùcè kuàijìshī", meaning: "公認会計士" },
      { hanzi: "资产负债表", pinyin: "zīchǎn fùzhàibiǎo", meaning: "貸借対照表" },
      { hanzi: "利润表", pinyin: "lìrùnbiǎo", meaning: "損益計算書" },
      { hanzi: "现金流量表", pinyin: "xiànjīn liúliàngbiǎo", meaning: "キャッシュフロー計算書" },
      { hanzi: "总账", pinyin: "zǒngzhàng", meaning: "総勘定元帳" },
      { hanzi: "明细账", pinyin: "míngxìzhàng", meaning: "補助元帳" },
      { hanzi: "凭证", pinyin: "píngzhèng", meaning: "伝票" },
      { hanzi: "记账", pinyin: "jìzhàng", meaning: "記帳" },
      { hanzi: "借方", pinyin: "jièfāng", meaning: "借方" },
      { hanzi: "贷方", pinyin: "dàifāng", meaning: "貸方" },
      { hanzi: "余额", pinyin: "yú'é", meaning: "残高" },
      { hanzi: "资产", pinyin: "zīchǎn", meaning: "資産" },
      { hanzi: "负债", pinyin: "fùzhài", meaning: "負債" },
      { hanzi: "所有者权益", pinyin: "suǒyǒuzhě quányì", meaning: "純資産(株主資本)" },
      { hanzi: "成本", pinyin: "chéngběn", meaning: "コスト・原価" },
      { hanzi: "收入", pinyin: "shōurù", meaning: "収入" },
      { hanzi: "支出", pinyin: "zhīchū", meaning: "支出" },
      { hanzi: "费用", pinyin: "fèiyòng", meaning: "費用" },
      { hanzi: "利润", pinyin: "lìrùn", meaning: "利益" },
      { hanzi: "净利润", pinyin: "jìnglìrùn", meaning: "純利益" },
      { hanzi: "毛利润", pinyin: "máolìrùn", meaning: "粗利益" },
      { hanzi: "折旧", pinyin: "zhéjiù", meaning: "減価償却" },
      { hanzi: "摊销", pinyin: "tānxiāo", meaning: "償却(無形資産)" },
      { hanzi: "应收账款", pinyin: "yīngshōu zhàngkuǎn", meaning: "売掛金" },
      { hanzi: "应付账款", pinyin: "yīngfù zhàngkuǎn", meaning: "買掛金" },
      { hanzi: "预收账款", pinyin: "yùshōu zhàngkuǎn", meaning: "前受金" },
      { hanzi: "预付账款", pinyin: "yùfù zhàngkuǎn", meaning: "前払金" },
      { hanzi: "固定资产", pinyin: "gùdìng zīchǎn", meaning: "固定資産" },
      { hanzi: "流动资产", pinyin: "liúdòng zīchǎn", meaning: "流動資産" },
      { hanzi: "流动负债", pinyin: "liúdòng fùzhài", meaning: "流動負債" },
      { hanzi: "长期负债", pinyin: "chángqī fùzhài", meaning: "固定負債" },
      { hanzi: "现金", pinyin: "xiànjīn", meaning: "現金" },
      { hanzi: "银行存款", pinyin: "yínháng cúnkuǎn", meaning: "銀行預金" },
      { hanzi: "库存现金", pinyin: "kùcún xiànjīn", meaning: "手許現金" },
      { hanzi: "预算", pinyin: "yùsuàn", meaning: "予算" },
      { hanzi: "决算", pinyin: "juésuàn", meaning: "決算" },
      { hanzi: "年度报告", pinyin: "niándù bàogào", meaning: "年次報告書" },
      { hanzi: "财务报表", pinyin: "cáiwù bàobiǎo", meaning: "財務諸表" },
      { hanzi: "税前利润", pinyin: "shuìqián lìrùn", meaning: "税引前利益" },
      { hanzi: "税后利润", pinyin: "shuìhòu lìrùn", meaning: "税引後利益" },
      { hanzi: "应纳税所得额", pinyin: "yīngnàshuì suǒdé'é", meaning: "課税所得" },
      { hanzi: "免税", pinyin: "miǎnshuì", meaning: "免税" },
      { hanzi: "退税", pinyin: "tuìshuì", meaning: "還付・戻し税" },
      { hanzi: "税收优惠", pinyin: "shuìshōu yōuhuì", meaning: "税制優遇" },
      { hanzi: "关联交易", pinyin: "guānlián jiāoyì", meaning: "関連者間取引" },
      { hanzi: "转让定价", pinyin: "zhuǎnràng dìngjià", meaning: "移転価格" },
      { hanzi: "双重征税", pinyin: "shuāngchóng zhēngshuì", meaning: "二重課税" },
      { hanzi: "税务协定", pinyin: "shuìwù xiédìng", meaning: "租税条約" },
      { hanzi: "汇算清缴", pinyin: "huìsuàn qīngjiǎo", meaning: "確定申告(年度精算)" },
      { hanzi: "预缴税款", pinyin: "yùjiǎo shuìkuǎn", meaning: "予定納税" },
      { hanzi: "滞纳金", pinyin: "zhìnàjīn", meaning: "延滞金" },
      { hanzi: "罚款", pinyin: "fákuǎn", meaning: "罰金" },
      { hanzi: "税务稽查", pinyin: "shuìwù jīchá", meaning: "税務調査" },
      { hanzi: "内部控制", pinyin: "nèibù kòngzhì", meaning: "内部統制" },
      { hanzi: "会计准则", pinyin: "kuàijì zhǔnzé", meaning: "会計基準" },
      { hanzi: "国际财务报告准则", pinyin: "guójì cáiwù bàogào zhǔnzé", meaning: "国際財務報告基準(IFRS)" },
      { hanzi: "成本核算", pinyin: "chéngběn hésuàn", meaning: "原価計算" },
      { hanzi: "预算编制", pinyin: "yùsuàn biānzhì", meaning: "予算編成" },
      { hanzi: "财务分析", pinyin: "cáiwù fēnxī", meaning: "財務分析" },
      { hanzi: "投资回报率", pinyin: "tóuzī huíbàolǜ", meaning: "投資収益率(ROI)" },
      { hanzi: "现金流", pinyin: "xiànjīnliú", meaning: "キャッシュフロー" },
      { hanzi: "应交税费", pinyin: "yīngjiāo shuìfèi", meaning: "未払税金" },
      { hanzi: "印花税", pinyin: "yìnhuāshuì", meaning: "印紙税" },
      { hanzi: "契税", pinyin: "qìshuì", meaning: "不動産取得税" },
      { hanzi: "关税完税价格", pinyin: "guānshuì wánshuì jiàgé", meaning: "課税価格" },
      { hanzi: "出口退税率", pinyin: "chūkǒu tuìshuìlǜ", meaning: "輸出戻し税率" },
      { hanzi: "税务筹划", pinyin: "shuìwù chóuhuà", meaning: "税務プランニング" },
      { hanzi: "会计年度", pinyin: "kuàijì niándù", meaning: "会計年度" },
      { hanzi: "财务负责人", pinyin: "cáiwù fùzérén", meaning: "財務責任者" },
      { hanzi: "出纳", pinyin: "chūnà", meaning: "出納係" },
      { hanzi: "对账", pinyin: "duìzhàng", meaning: "照合(勘定合わせ)" },
      { hanzi: "报销", pinyin: "bàoxiāo", meaning: "経費精算" },
      { hanzi: "差旅费", pinyin: "chāilǚfèi", meaning: "出張費" },
      { hanzi: "招待费", pinyin: "zhāodàifèi", meaning: "接待費" },
      { hanzi: "工资", pinyin: "gōngzī", meaning: "給与" },
      { hanzi: "社保", pinyin: "shèbǎo", meaning: "社会保険" },
      { hanzi: "公积金", pinyin: "gōngjījīn", meaning: "住宅積立金" },
      { hanzi: "发薪日", pinyin: "fāxīnrì", meaning: "給料日" },
      { hanzi: "结算", pinyin: "jiésuàn", meaning: "決済・精算" },
      { hanzi: "合并报表", pinyin: "hébìng bàobiǎo", meaning: "連結財務諸表" },
      { hanzi: "母公司", pinyin: "mǔ gōngsī", meaning: "親会社" },
      { hanzi: "子公司", pinyin: "zǐ gōngsī", meaning: "子会社" },
      { hanzi: "外资企业", pinyin: "wàizī qǐyè", meaning: "外資企業" },
      { hanzi: "税务代理", pinyin: "shuìwù dàilǐ", meaning: "税務代理" },
    ],
  },
  {
    id: "news",
    label: "経済ニュース",
    icon: "📰",
    description: "財新(caixin)や中国テック系ニュースを読むための時事・企業用語",
    words: [
      { hanzi: "经济", pinyin: "jīngjì", meaning: "経済" },
      { hanzi: "金融", pinyin: "jīnróng", meaning: "金融" },
      { hanzi: "政经", pinyin: "zhèngjīng", meaning: "政治経済" },
      { hanzi: "观点", pinyin: "guāndiǎn", meaning: "論説・見解" },
      { hanzi: "数据", pinyin: "shùjù", meaning: "データ" },
      { hanzi: "订阅", pinyin: "dìngyuè", meaning: "購読する" },
      { hanzi: "科技", pinyin: "kējì", meaning: "科学技術" },
      { hanzi: "地产", pinyin: "dìchǎn", meaning: "不動産" },
      { hanzi: "消费", pinyin: "xiāofèi", meaning: "消費" },
      { hanzi: "能源", pinyin: "néngyuán", meaning: "エネルギー" },
      { hanzi: "环保", pinyin: "huánbǎo", meaning: "環境保護" },
      { hanzi: "民生", pinyin: "mínshēng", meaning: "民生・暮らし" },
      { hanzi: "专题", pinyin: "zhuāntí", meaning: "特集" },
      { hanzi: "访谈", pinyin: "fǎngtán", meaning: "インタビュー" },
      { hanzi: "周刊", pinyin: "zhōukān", meaning: "週刊誌" },
      { hanzi: "应届毕业生", pinyin: "yīngjiè bìyè shēng", meaning: "新卒者" },
      { hanzi: "辞退", pinyin: "cítuì", meaning: "解雇する・辞退させる" },
      { hanzi: "批量", pinyin: "pīliàng", meaning: "大量に・一括で" },
      { hanzi: "校招", pinyin: "xiàozhāo", meaning: "新卒採用(校园招聘の略)" },
      { hanzi: "入职", pinyin: "rùzhí", meaning: "入社する" },
      { hanzi: "录用通知", pinyin: "lùyòng tōngzhī", meaning: "内定通知" },
      { hanzi: "人力资源部", pinyin: "rénlì zīyuán bù", meaning: "人事部" },
      { hanzi: "约谈", pinyin: "yuētán", meaning: "呼び出して話をする" },
      { hanzi: "招聘", pinyin: "zhāopìn", meaning: "採用する・募集する" },
      { hanzi: "跨国企业", pinyin: "kuàguó qǐyè", meaning: "多国籍企業" },
      { hanzi: "品牌价值", pinyin: "pǐnpái jiàzhí", meaning: "ブランド価値" },
      { hanzi: "同比", pinyin: "tóngbǐ", meaning: "前年比" },
      { hanzi: "销售额", pinyin: "xiāoshòu é", meaning: "売上高" },
      { hanzi: "估值", pinyin: "gūzhí", meaning: "評価額(バリュエーション)" },
      { hanzi: "融资", pinyin: "róngzī", meaning: "資金調達" },
      { hanzi: "上市", pinyin: "shàngshì", meaning: "上場する" },
      { hanzi: "董事长", pinyin: "dǒngshìzhǎng", meaning: "会長・董事長" },
      { hanzi: "首席执行官", pinyin: "shǒuxí zhíxíngguān", meaning: "最高経営責任者(CEO)" },
      { hanzi: "创业公司", pinyin: "chuàngyè gōngsī", meaning: "スタートアップ" },
      { hanzi: "初创企业", pinyin: "chūchuàng qǐyè", meaning: "新興企業" },
      { hanzi: "量产", pinyin: "liàngchǎn", meaning: "量産" },
      { hanzi: "全固态电池", pinyin: "quán gùtài diànchí", meaning: "全固体電池" },
      { hanzi: "芯片", pinyin: "xīnpiàn", meaning: "半導体チップ" },
      { hanzi: "人工智能", pinyin: "réngōng zhìnéng", meaning: "人工知能(AI)" },
      { hanzi: "机器人", pinyin: "jīqìrén", meaning: "ロボット" },
      { hanzi: "人形机器人", pinyin: "rénxíng jīqìrén", meaning: "ヒューマノイドロボット" },
      { hanzi: "电动汽车", pinyin: "diàndòng qìchē", meaning: "電気自動車(EV)" },
      { hanzi: "自动驾驶", pinyin: "zìdòng jiàshǐ", meaning: "自動運転" },
      { hanzi: "新能源汽车", pinyin: "xīn néngyuán qìchē", meaning: "新エネルギー車(NEV)" },
      { hanzi: "光伏", pinyin: "guāngfú", meaning: "太陽光発電" },
      { hanzi: "装机容量", pinyin: "zhuāngjī róngliàng", meaning: "設備容量" },
      { hanzi: "经常性收入", pinyin: "jīngchángxìng shōurù", meaning: "経常収益(ARR)" },
      { hanzi: "投资", pinyin: "tóuzī", meaning: "投資" },
      { hanzi: "投后估值", pinyin: "tóuhòu gūzhí", meaning: "投資後評価額(ポストマネー)" },
      { hanzi: "天使轮", pinyin: "tiānshǐlún", meaning: "エンジェルラウンド" },
      { hanzi: "独角兽", pinyin: "dújiǎoshòu", meaning: "ユニコーン企業" },
      { hanzi: "出海", pinyin: "chūhǎi", meaning: "海外進出する" },
      { hanzi: "海外营收", pinyin: "hǎiwài yíngshōu", meaning: "海外売上高" },
      { hanzi: "涨幅", pinyin: "zhǎngfú", meaning: "上昇率・伸び率" },
      { hanzi: "跌幅", pinyin: "diēfú", meaning: "下落率" },
      { hanzi: "市场份额", pinyin: "shìchǎng fèn'é", meaning: "市場シェア" },
      { hanzi: "龙头企业", pinyin: "lóngtóu qǐyè", meaning: "業界トップ企業" },
      { hanzi: "智库", pinyin: "zhìkù", meaning: "シンクタンク" },
      { hanzi: "报告", pinyin: "bàogào", meaning: "レポート・報告書" },
      { hanzi: "排行榜", pinyin: "páixíngbǎng", meaning: "ランキング" },
      { hanzi: "供不应求", pinyin: "gōng bú yìng qiú", meaning: "供給が需要に追いつかない" },
      { hanzi: "副总裁", pinyin: "fù zǒngcái", meaning: "副社長" },
      { hanzi: "执行副总裁", pinyin: "zhíxíng fù zǒngcái", meaning: "執行副社長" },
      { hanzi: "半年报", pinyin: "bànniánbào", meaning: "中間決算報告" },
      { hanzi: "年报", pinyin: "niánbào", meaning: "年次報告書" },
      { hanzi: "营业额", pinyin: "yíngyè é", meaning: "営業高(売上高)" },
    ],
  },
];
